export let english = {
  PRIMARY_FOCUS: 'Primary focus — based on primary indexes',
  FURTHER_TESTING: 'Further testing suggested',
  SECONDARY_FOCUS: 'Secondary focus — based on supportive indexes',
  PRIMARY_TITLE_1: 'Maintain and protect current inflammation regulation and immune aging',
  PRIMARY_DESC_1: "Evaluate whether these optimal results are driven by pharmaceutical interventions (e.g., HRT, TRT, thyroxine, incretin therapies such as GLP-1 agonists, anti-inflammatories), favorable genetic traits (e.g., longevity-associated or glycan-beneficial variants), or lifestyle factors. If risk factors or chronic conditions are present, this profile confirms that current strategies are successfully controlling inflammation.",
  PRIMARY_FURTHER_1: 'None beyond standard annual preventive labs unless new symptoms emerge.',
  PRIMARY_TITLE_2: 'Minimize low-grade inflammatory triggers to prevent further immune system aging',
  PRIMARY_DESC_2: 'To mitigate ongoing immune activation, assess for potential triggers such as recent or unresolved infections. Focus on reducing pro-inflammatory foods, correcting energy imbalances, and limiting alcohol intake. Reinforce consistent sleep patterns and provide strategies to support stress regulation and recovery.',
  PRIMARY_FURTHER_2: 'Consider hs-CRP and other inflammatory markers, 25-hydroxy vitamin D, ferritin, and iron studies. Assess lipid profile and fasting glucose–insulin to evaluate cardiometabolic load.',
  PRIMARY_TITLE_3: 'Optimize physical activity to support immune youthfulness',
  PRIMARY_DESC_3: 'Encourage a balanced training approach by limiting excessive higher-intensity cardio, incorporating or maintaining strength training, and prioritizing recovery strategies to support long-term immune youthfulness. If there is a personal or family history of autoimmune conditions, monitor Glycan Youth trends closely, as maintaining this index may be particularly important in genetically susceptible individuals.',
  PRIMARY_FURTHER_3: 'If there is a personal or family history of autoimmune or inflammatory conditions, evaluate ESR, hs-CRP, ANA screen, and baseline thyroid function (TSH, fT4, fT3). Monitor vitamin D status.',
  PRIMARY_TITLE_4: 'Support resolution pathways through gut, nutrition, and fitness',
  PRIMARY_DESC_4: 'Focus on improving gut health with targeted probiotics, prebiotics, and fiber diversity, increase the nutrient density of the diet through whole foods and anti-inflammatory compounds, assess for micronutrient deficiencies if needed, and support overall immune resilience by enhancing physical fitness.',
  PRIMARY_FURTHER_4: 'Consider micronutrient evaluation (omega-3 index, zinc, magnesium, vitamin D, B12, folate), hs-CRP, and targeted gut health assessment (stool analysis, microbiome profile, or permeability markers) if clinical suspicion exists.',
  PRIMARY_TITLE_5: 'Counterbalance high-demand lifestyles with structured recovery',
  PRIMARY_DESC_5: 'Support the client in establishing consistent rest routines, strengthening stress regulation strategies, and aligning daily habits with circadian rhythms. For individuals in high-pressure environments, implement practical recovery tools, such as scheduled downtime, breathwork, or short movement breaks, to buffer the immune system from ongoing load. Monitor cardiometabolic health markers and address any early signs of imbalance to prevent further strain on the immune system.',
  PRIMARY_FURTHER_5: 'Evaluate lipid profile, hs-CRP, 25-hydroxy vitamin D, fasting glucose–insulin, ANA screen. Consider assessment of sleep quality and HRV for recovery monitoring.',
  PRIMARY_TITLE_6: 'Strengthen vascular resilience through targeted lifestyle support',
  PRIMARY_DESC_6: 'Recommend a dietary pattern emphasizing omega-3 sources, nitrate-containing vegetables, and polyphenol-rich foods, while limiting processed foods, excess sodium, and added sugars. Advise the client to engage in regular moderate-intensity aerobic activity alongside consistent recovery and sleep routines. Monitor cardiovascular health, particularly if there is a personal or family history of cardiovascular conditions.',
  PRIMARY_FURTHER_6: 'Check lipid profile, blood pressure (including variability), hs-CRP, and fasting glucose–insulin. Consider Omega-3 Index and homocysteine for cardiovascular support planning.',
  PRIMARY_TITLE_7: 'Improve immune responsiveness by supporting recovery, rhythm, and core systems',
  PRIMARY_DESC_7: 'Recommend implementing structured wind-down routines and consistent bedtimes to stabilise circadian rhythm, incorporate active recovery strategies, and support gut and liver health through increased fiber diversity, cruciferous vegetables, and evidence-based nutritional compounds known to enhance immune system regulation.',
  PRIMARY_FURTHER_7: 'Micronutrient profile (zinc, magnesium, vitamin D, B12, folate, omega-3 index), hs-CRP, fasting glucose–insulin. If symptoms persist, evaluate sex hormones and thyroid function for systemic recovery impact.',
  PRIMARY_TITLE_8: 'Shift early immune aging with targeted, system-wide intervention',
  PRIMARY_DESC_8: 'Recommend structured improvements in nutrition (e.g. anti-inflammatory, nutrient-dense meals with stable energy balance), increase physical activity with both aerobic and resistance training, reinforce consistent, high-quality sleep, and implement daily stress recovery practices. This pattern may signal early metabolic strain, so a more deliberate and comprehensive intervention is warranted to restore immune resilience.',
  PRIMARY_FURTHER_8: 'Full cardiometabolic panel (lipids, glucose–insulin, hs-CRP), vitamin D, and selected micronutrients, ANA screen. Consider baseline hormone evaluation if lifestyle strain is prolonged.',
  PRIMARY_TITLE_9: 'Lower chronic inflammatory burden to slow biological aging',
  PRIMARY_DESC_9: 'Prioritize reducing inflammatory load through an anti-inflammatory, metabolically balanced diet, address central drivers like insulin resistance, dyslipidaemia, or hormonal imbalance, and implement daily stress regulation strategies.',
  PRIMARY_FURTHER_9: 'Assess blood pressure, glucose control, lipid panel, hormone status, and systemic inflammatory markers to guide targeted intervention.',
  PRIMARY_TITLE_10: 'Restore immune adaptability by targeting core metabolic and regulatory systems',
  PRIMARY_DESC_10: 'Improve body composition, stabilise circadian rhythm, and optimize energy intake. Encourage a balanced training approach by limiting excessive cardio, introducing or maintaining strength training, and prioritizing recovery strategies. If there is a personal or family history of autoimmune conditions, monitor Glycan Youth trends closely.',
  PRIMARY_FURTHER_10: 'Consider evaluating markers of metabolic health, sex hormone levels, and autoimmunity to uncover potential underlying drivers.',
  PRIMARY_TITLE_11: 'Improve inflammation resolution by restoring gut–nutrient–stress axis',
  PRIMARY_DESC_11: 'Support gut integrity through increased fiber diversity, fermented foods, and digestive assessment if needed; optimize micronutrients and glycan precursors (e.g. zinc, magnesium, omega-3, vitamin D); and reduce cumulative stress through consistent recovery routines and circadian alignment.',
  PRIMARY_FURTHER_11: 'Consider investigating digestive function, systemic inflammation, and sex hormone balance to identify and correct underlying barriers to immune resolution.',
  PRIMARY_TITLE_12: 'Reverse chronic inflammation by targeting metabolic and immune overload',
  PRIMARY_DESC_12: 'Recommend a structured anti-inflammatory protocol focused on improving metabolic health, optimizing body composition, stabilising blood sugar, and reducing dietary and lifestyle-driven inflammatory triggers.',
  PRIMARY_FURTHER_12: 'Evaluate blood pressure, lipid status, sex hormone balance, and systemic inflammation to identify key drivers and implement targeted interventions that can reverse the immune aging trajectory.',
  PRIMARY_TITLE_13: 'Lower immune load by reducing inflammatory triggers and enhancing recovery',
  PRIMARY_DESC_13: 'Focus on improving gut health, limiting exposure to dietary and environmental toxins, and eliminating processed, pro-inflammatory foods.',
  PRIMARY_FURTHER_13: 'Assess blood pressure, glycemic control, lipid profile, sex hormone status, and systemic inflammation to guide targeted interventions that protect long-term immune resilience and prevent immune aging.',
  PRIMARY_TITLE_14: 'Support immune recovery by rebuilding core regulatory capacity',
  PRIMARY_DESC_14: 'Focus on improving body composition while avoiding overtraining, emphasize movement quality and sufficient recovery, stabilise circadian rhythm through regular sleep–wake cycles, and address energy status with a diverse, anti-inflammatory diet.',
  PRIMARY_FURTHER_14: 'Evaluate metabolic markers, hormone levels, and autoimmune risk to uncover and address deeper drivers of immune aging.',
  PRIMARY_TITLE_15: 'Rebuild immune youth by balancing stress, movement, and recovery',
  PRIMARY_DESC_15: 'Support recovery through consistent sleep–wake timing, moderate and well-balanced physical activity, and structured rest routines. Ensure adequate nourishment and optimize daily energy intake.',
  PRIMARY_FURTHER_15: 'Evaluate metabolic markers, thyroid function, hormone levels, and autoimmune risk to uncover and address deeper drivers of immune aging.',
  PRIMARY_TITLE_16: 'Strengthen immune regulation by supporting gut integrity and reducing immune irritants',
  PRIMARY_DESC_16: 'Focus on improving gut health through fiber diversity and microbiome-supportive strategies, support detoxification and elimination pathways, and reduce exposure to common immune irritants such as alcohol, food sensitivities, and environmental toxins.',
  PRIMARY_FURTHER_16: 'Consider evaluating digestive markers (e.g. microbiome profile, zonulin), systemic inflammation, key micronutrients, sex hormone balance, and autoantibodies when indicated.',
  PRIMARY_TITLE_17: 'Improve immune recovery by supporting gut–liver axis and nutritional sufficiency',
  PRIMARY_DESC_17: 'Strengthen gut and liver function through fiber-rich, anti-inflammatory foods and targeted support as needed, reinforce structured recovery routines, and ensure adequate intake of key micronutrients and glycan-building nutrients.',
  PRIMARY_FURTHER_17: 'Consider assessing iron status, B12, folate, vitamin D, zinc, magnesium, and digestive function (e.g. microbiome profile, stool markers, zonulin); screen for autoantibodies if autoimmune risk is present.',
  PRIMARY_TITLE_18: 'Reduce inflammatory burden through systemic lifestyle and environmental interventions',
  PRIMARY_DESC_18: 'Recommend a nutrient-dense, anti-inflammatory diet; restore sleep–wake rhythm; reinforce daily stress regulation; introduce consistent, moderate physical activity; and prioritize body composition improvement to reduce metabolic strain. To lower cumulative immune load, reduce environmental exposures such as alcohol, endocrine disruptors, and pollutants.',
  PRIMARY_FURTHER_18: 'Assess cardiometabolic markers, hormone balance, systemic inflammation, and autoimmune panels if indicated.',
  PRIMARY_TITLE_19: 'Rebuild immune resilience by rebalancing stress, movement, and nutrition',
  PRIMARY_DESC_19: 'Support deeper recovery through consistent sleep–wake cycles and structured rest, and help find an appropriate balance between physical activity and recovery to avoid over- or undertraining. Optimize macro- and micronutrient intake, particularly protein, minerals, and anti-inflammatory compounds, and evaluate thyroid function, cortisol rhythm, insulin sensitivity, body composition, and sleep quality to identify key contributors to immune decline.',
  PRIMARY_FURTHER_19: 'CBC, liver/kidney panels, inflammatory markers, glucose–insulin panel, full thyroid and adrenal assessment, vitamin D, gut function (stool, microbiome, breath test), toxin screen, and autoimmune markers as indicated. Functional metrics such as HRV, VO₂max, and body composition may also help track recovery.',
  PRIMARY_TITLE_20: 'Restore immune resolution by supporting gut health and recovery signals',
  PRIMARY_DESC_20: 'Focus on gut repair through fiber diversity and microbiome-supportive strategies, reduce immune irritants such as processed foods, alcohol, and environmental toxins, and reinforce the body’s recovery capacity with consistent sleep, gentle movement, and structured stress-regulation routines.',
  PRIMARY_FURTHER_20: 'Consider evaluating gut permeability or microbiome balance, nutrient absorption (zinc, magnesium, B vitamins), cortisol rhythm, and other signs of barrier dysfunction.',
  PRIMARY_TITLE_21: 'Rebuild immune balance by restoring circadian rhythm and hormonal regulation',
  PRIMARY_DESC_21: 'A comprehensive health evaluation is recommended to investigate underlying contributors. Prioritize circadian alignment with consistent sleep–wake schedules, integrate brief but regular recovery practices during the workday (e.g. short walks, breathwork, movement breaks), and avoid overreliance on high-intensity exercise in favour of balanced strength and mobility training. Address central drivers of immune disruption like hypertension, insulin resistance, dyslipidaemia, or hormonal imbalance.',
  PRIMARY_FURTHER_21: 'CBC, liver and kidney panels, lipid profile, glucose–insulin panel, full thyroid, adrenal, and sex hormone assessment, inflammatory markers (including hs-CRP), vitamin D, iron status, B12, folate, magnesium, zinc, homocysteine, Omega-3 Index, gut function tests (stool analysis, microbiome, breath tests), and autoimmune markers if indicated. Functional metrics such as HRV, VO₂max, and body composition can also support tracking of recovery.',
  PRIMARY_TITLE_22: 'Lower systemic inflammatory load and protect cardiovascular health',
  PRIMARY_DESC_22: 'A comprehensive health evaluation is recommended to investigate underlying contributors. Implement an anti-inflammatory, nutrient-dense diet and address oral and gut health to remove potential sources of persistent immune activation. emphasize cardiovascular support through regular, moderate physical activity, stress regulation, and optimal sleep.',
  PRIMARY_FURTHER_22: 'CBC, liver and kidney panels, lipid profile, glucose–insulin panel, full thyroid, adrenal, and sex hormone assessment, inflammatory markers (including hs-CRP), vitamin D, iron status, B12, folate, magnesium, zinc, homocysteine, Omega-3 Index, gut function tests (stool analysis, microbiome, breath tests), and autoimmune markers if indicated. Functional metrics such as HRV, VO₂max, and body composition can also support tracking of recovery.',
  PRIMARY_TITLE_23: 'Rebuild immune adaptability through restoration and resilience',
  PRIMARY_DESC_23: 'A comprehensive health evaluation is recommended to investigate underlying contributors. Focus on replenishing nutrient reserves with a diverse, protein- and micronutrient-rich diet, support digestive health to optimize absorption, and implement structured recovery through consistent sleep, stress regulation, and gentle, progressive physical activity.',
  PRIMARY_FURTHER_23: 'CBC, liver and kidney panels, lipid profile, glucose–insulin panel, full thyroid, adrenal, and sex hormone assessment, inflammatory markers (including hs-CRP), vitamin D, iron status, B12, folate, magnesium, zinc, homocysteine, Omega-3 Index, gut function tests (stool analysis, microbiome, breath tests), and autoimmune markers if indicated. Functional metrics such as HRV, VO₂max, and body composition can also support tracking of recovery.',
  PRIMARY_TITLE_24: 'Address root drivers of systemic immune strain and chronic inflammation',
  PRIMARY_DESC_24: 'A comprehensive health evaluation is recommended to investigate underlying contributors. Focus on removing inflammatory load (from diet, environment, gut), rebuilding recovery capacity (through sleep, nutrition, stress regulation), and restoring metabolic and hormonal balance.',
  PRIMARY_FURTHER_24: 'CBC, liver and kidney panels, lipid profile, glucose–insulin panel, full thyroid, adrenal, and sex hormone assessment, inflammatory markers (including hs-CRP), vitamin D, iron status, B12, folate, magnesium, zinc, homocysteine, Omega-3 Index, gut function tests (stool analysis, microbiome, breath tests), and autoimmune markers if indicated. Functional metrics such as HRV, VO₂max, and body composition can also support tracking of recovery.',
  PRIMARY_TITLE_25: 'Address root drivers of systemic immune strain and chronic inflammation',
  PRIMARY_DESC_25: 'A comprehensive health evaluation is recommended to investigate underlying contributors. Evaluate and address gut/barrier dysfunction, endocrine imbalance, toxin exposures, and chronic stress; reduce dietary and environmental inflammatory load while reinforcing sleep, targeted nutrition, and stress‑regulation to re‑establish resolution capacity.',
  PRIMARY_FURTHER_25: 'CBC, liver and kidney panels, lipid profile, glucose–insulin panel, full thyroid, adrenal, and sex hormone assessment, inflammatory markers (including hs-CRP), vitamin D, iron status, B12, folate, magnesium, zinc, homocysteine, Omega-3 Index, gut function tests (stool analysis, microbiome, breath tests), and autoimmune markers if indicated. Functional metrics such as HRV, VO₂max, and body composition can also support tracking of recovery.',
  PRIMARY_TITLE_26: 'Rebuild immune adaptability through restoration and resilience',
  PRIMARY_DESC_26: 'A comprehensive health evaluation is recommended to investigate underlying contributors. Focus on replenishing nutrient reserves with a diverse, protein- and micronutrient-rich diet, support digestive health to optimize absorption, and implement structured recovery through consistent sleep, stress regulation, and gentle, progressive physical activity. Make efforts to restore metabolic and hormonal balance.',
  PRIMARY_FURTHER_26: 'CBC, liver and kidney panels, lipid profile, glucose–insulin panel, full thyroid, adrenal, and sex hormone assessment, inflammatory markers (including hs-CRP), vitamin D, iron status, B12, folate, magnesium, zinc, homocysteine, Omega-3 Index, gut function tests (stool analysis, microbiome, breath tests), and autoimmune markers if indicated. Functional metrics such as HRV, VO₂max, and body composition can also support tracking of recovery.',
  PRIMARY_TITLE_27: 'Reduce inflammatory burden and restore systemic resilience',
  PRIMARY_DESC_27: 'A comprehensive health evaluation is recommended to investigate underlying contributors. Focus on removing inflammatory load (from diet, environment, gut), rebuilding recovery capacity (through sleep, nutrition, stress regulation), and restoring metabolic and hormonal balance.',
  PRIMARY_FURTHER_27: 'CBC, liver and kidney panels, lipid profile, glucose–insulin panel, full thyroid, adrenal, and sex hormone assessment, inflammatory markers (including hs-CRP), vitamin D, iron status, B12, folate, magnesium, zinc, homocysteine, Omega-3 Index, gut function tests (stool analysis, microbiome, breath tests), and autoimmune markers if indicated. Functional metrics such as HRV, VO₂max, and body composition can also support tracking of recovery.',
  SUPPORTIVE_TITLE_1: 'Reduce systemic and environmental strain to stabilise vascular–respiratory resilience',
  SUPPORTIVE_DESC_1: 'Address autonomic stress by improving circadian alignment, enforcing structured recovery routines, and minimizing environmental exposures such as poor air quality, smoking, or occupational irritants. Support cardiovascular and respiratory health with moderate aerobic conditioning and regular monitoring of blood pressure and lung function.',
  SUPPORTIVE_FURTHER_1: 'Blood pressure assessment (including variability), lung function testing, full cardiometabolic panel. Consider advanced vascular imaging if risk factors or family history indicate. Where relevant, conduct sleep studies to rule out sleep apnoea and assess autonomic regulation using HRV or similar metrics.',
  SUPPORTIVE_TITLE_2: 'Enhance vascular resilience and stabilise autonomic function',
  SUPPORTIVE_DESC_2: 'Maintain regular aerobic and resistance training, and improve recovery quality by addressing sleep and stress regulation. Minimise factors that impair vascular function, such as excessive alcohol, high-sodium diets, or unmanaged blood pressure.',
  SUPPORTIVE_FURTHER_2: 'Cardiovascular screening with blood pressure monitoring (including variability), lipid profiling, glucose–insulin testing. Assess circadian rhythm stability and recovery capacity through sleep quality assessment and HRV tracking, and consider advanced vascular imaging if risk factors or family history indicate.',
  SUPPORTIVE_TITLE_3: 'Address vascular vulnerability and monitor for early disease markers',
  SUPPORTIVE_DESC_3: 'Strengthen vascular integrity through a cardioprotective diet, regular aerobic activity, and maintaining optimal blood pressure and lipid balance. Consider targeted screening if family history is present.',
  SUPPORTIVE_FURTHER_3: 'Lipid profiling, glucose–insulin assessment, hsCRP, and advanced cardiovascular risk screening (e.g., coronary calcium scoring or carotid intima-media thickness) when indicated. Autoimmune panels may be considered if clinical history or primary indexes suggest an autoimmune profile.',
  SUPPORTIVE_TITLE_4: 'Reduce environmental stress load',
  SUPPORTIVE_DESC_4: 'Reduce inflammatory triggers, improve air quality, manage stress, and optimizing body composition.',
  SUPPORTIVE_FURTHER_4: 'Smoking status confirmation, blood pressure variation, HRV for stress load, sleep quality assessment, environmental toxin review, and body composition analysis.',
  SUPPORTIVE_TITLE_5: 'Maintain balance and monitor',
  SUPPORTIVE_DESC_5: 'Review lifestyle rhythm, nutrient sufficiency, and signs of subtle cardiovascular or respiratory pressure.',
  SUPPORTIVE_FURTHER_5: 'Reassess blood pressure and HRV periodically to track stability.',
  SUPPORTIVE_TITLE_6: 'Support vascular stability',
  SUPPORTIVE_DESC_6: 'Maintain cardiovascular hygiene and monitor trends over time.',
  SUPPORTIVE_FURTHER_6: 'Check blood pressure and lipid profile at routine intervals.',
  SUPPORTIVE_TITLE_7: 'Reduce environmental stress load',
  SUPPORTIVE_DESC_7: 'Address toxin exposure, sleep disruption, and respiratory strain.',
  SUPPORTIVE_FURTHER_7: 'Assess blood pressure variation, HRV, sleep quality, and environmental toxin exposure profile.',
  SUPPORTIVE_TITLE_8: 'Prevent escalation of autonomic strain',
  SUPPORTIVE_DESC_8: 'Encourage continued support for circadian rhythm, respiratory hygiene, and stress-reducing lifestyle practices. Follow up if symptoms emerge or primary indexes shift unfavorably.',
  SUPPORTIVE_FURTHER_8: 'Periodically assess blood pressure, HRV and sleep patterns.',
  SUPPORTIVE_TITLE_9: 'Maintain optimal supportive balance',
  SUPPORTIVE_DESC_9: 'Continue current preventive strategies and monitor periodically.',
  SUPPORTIVE_FURTHER_9: 'No additional testing unless primary indexes indicate otherwise.',
  BIOLOGICAL_AGE: 'Biological age',
  CHRONOLOGICAL_AGE: 'Chronological age',
  CHRONOLOGICAL_AGE_TWO: 'chronological age',
  SI_SCORE: 'SI score',
  GLYCAN: 'Glycan',
  PEAK: 'Peak',
  LOWER_THAN_AVERAGE: 'Lower than average',
  BELOW_AVERAGE: 'Below average',
  AROUND_AVERAGE: 'Around average',
  HIGHER_THAN_AVERAGE: 'Higher than average',
  ABOVE_AVERAGE: 'Above average',
  SOME_OVERLAP_LONG: 'Some overlap',
  MINOR_OVERLAP_LONG: 'Minor overlap',
  NO_OVERLAP_LONG: 'No significant overlap',
  SOME_OVERLAP: 'Some overlap',
  MINOR_OVERLAP: 'Minor overlap',
  NO_OVERLAP: 'No significant overlap',
  OVERLAP_TEXT: 'of glycan indexes between your patient and this condition.',
  SYMPTOMS: 'Signs and symptoms',
  SYMPTOM_ONE: 'Usually asymptomatic',
  SYMPTOM_TWO: 'BP consistently >140/90 mmHg',
  SYMPTOM_THREE: 'Signs of malignant hypertension (headache, dizziness, breathlessness, etc.)',
  SYMPTOM_FOUR: 'Signs of coronary artery disease (e.g., self-resolving chest pain, breathlessness)',
  SYMPTOM_FIVE: 'Signs of peripheral artery disease (e.g., leg pain during activity)',
  SYMPTOM_SIX: 'Self-limiting chest pain ± radiation into jaw/left arm/back',
  SYMPTOM_SEVEN: 'Breathlessness',
  SYMPTOM_EIGHT: 'Other (syncope, palpitations, leg edema, orthopnea, etc.)',
  SYMPTOM_NINE: 'Abdominal pain and cramping/left arm/back',
  SYMPTOM_TEN: 'Recurring diarrhea (± blood)',
  SYMPTOM_TEN_B: 'Urgency to defecate',
  SYMPTOM_ELEVEN: 'Weight loss',
  SYMPTOM_TWELVE: 'Systemic (e.g., fatigue, weight loss, mouth ulcers, butterfly skin rash)',
  SYMPTOM_THIRTEEN: 'Organ-specific (chest pain, difficulty breathing, leg swelling, anaemia, etc.)',
  SYMPTOM_FOURTEEN: 'Joint pain and swelling',
  SYMPTOM_FIFTEEN: 'Fatigue',
  SYMPTOM_SIXTEEN: 'Increased thirst and frequent urination',
  SYMPTOM_SEVENTEEN: 'Slow wound healing, blurred vision, frequent thrush',
  SYMPTOM_EIGHTEEN: 'Difficulty breathing',
  SYMPTOM_NINETEEN: 'Chronic cough (± productive)',
  SYMPTOM_TWENTY: 'Irregular menstrual cycle',
  SYMPTOM_TWENTYONE: 'Vasomotor symptoms (e.g., hot flushes, night sweats)',
  SYMPTOM_TWENTYTWO: 'Other (e.g., mood swings, cognitive difficulties, sleep disturbance)',
  SYMPTOM_TWENTYTHREE: 'Joint pain, swelling, stiffness and erythema',
  SYMPTOM_TWENTYFOUR: 'Smaller and distant joint involvement (fingers, toes), usually symmetrical',
  SYMPTOM_TWENTYFIVE: 'Systemic (fatigue, weight loss, etc.)',
  POSSIBLE_FOLLOW_UP: 'Possible follow-up',
  POSSIBLE_FOLLOW_UP_ONE: 'Serial blood pressure (BP) measurements Â± 24-hour BP monitoring',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI and/or body composition check',
  POSSIBLE_FOLLOW_UP_THREE: 'Basic bloods (lipid profile, renal and liver function)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Blood tests: basic and extended lipid profile (e.g., Lp(a), ApoB), hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'BP check',
  POSSIBLE_FOLLOW_UP_SIX: 'ECG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Cardiology referral for other tests (e.g., cardiac echo, coronary CT)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Cardiology referral for other tests (e.g., coronary artery calcium score)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Cardiology referral for other tests (e.g., stress echocardiogram)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Blood tests: full blood count, renal and liver function, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Stool tests: faecal immunochemical test (FIT), faecal calprotectin',
  POSSIBLE_FOLLOW_UP_TEN: 'Referral for CT colonoscopy',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Blood tests: full blood count, renal and liver function, CRP, ESR, autoantibodies (e.g., ANA, anti-dsDNA)',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Urinalysis',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Organ-targeted imaging (e.g., CT thorax, CT abdomen)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Blood tests: full blood count, renal and liver function, fasting glucose and insulin, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Lipid profile blood tests: basic and extended (incl. oxLDL, VLDL, LDL-P, Lp-PLA2, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Other blood tests hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Blood tests: full blood count',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometry',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'ECG, chest X-ray',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Blood tests (incl. FSH, oestradiol, progesterone, testosterone, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Referral to (peri)menopause specialist/gynaecologist',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Blood tests: full blood count, rheumatoid factor, anti-CCP antibodies, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Joint imaging (X-rays, MRI)',
  PERCENTILE: 'percentile',
  SINGLE_PERCENTILE: 'percentile',
  RISK_FACTORS: 'Risk factors',
  RISK_FACTOR_ONE: 'Past medical history (cardiometabolic syndrome, autoimmune disease)',
  RISK_FACTOR_TWO: 'Medication history (e.g., statins, blood thinners)',
  RISK_FACTOR_THREE: 'Current/previous smoking history',
  RANKS_YOU: 'This result ranks you in the',
  THIS_RESULT_RANKS_IN_THE: 'This result ranks in the',
  RELATED_RESEARCH_PAPERS: 'Related research papers',
  YOUR_RESULT: 'Your result',
  CHRONIC_INFLAMMATION: 'Chronic inflammation',
  SYSTEMIC_INFLAMMATION: 'Systemic inflammation',
  ANTI_INFLAMMATORY: 'Anti-inflammatory',
  ANTI_INFLAMMATORY_INDEX: 'Anti-inflammatory index',
  PRO_INFLAMMATORY: 'Pro-inflammatory',
  PRO_INFLAMMATORY_INDEX: 'Pro-inflammatory index',
  SUPPORTIVE_INDEX: 'Supportive index',
  GLYCAN_SHIELD: 'Glycan Shield (S)',
  GLYCAN_YOUTH: 'Glycan Youth (G2)',
  GLYCAN_MATURE: 'Glycan Mature (G0)',
  GLYCAN_MEDIAN: 'Glycan Median (G1)',
  GLYCAN_LIFESTYLE: 'Glycan Lifestyle (B)',
  GLYCAN_LIFESTYLE_B: 'Glycan Bisection (B)',
  WORSE: 'Worse',
  BETTER: 'Better',
  OPTIMAL: 'Optimal',
  SUBOPTIMAL: 'Suboptimal',
  AVERAGE: 'Average',
  INDEX_SCORE: 'Index score',
  MEASURED_RESULT: 'Measured result',
  POPULATION_AVERAGE: 'Population average',
  AGE: 'Age',
  SAME_AS: 'Same as',
  THAN: 'than',
  YEAR_OLDER: 'year older',
  YEARS_OLDER: 'years older',
  YEAR_YOUNGER: 'year younger',
  YEARS_YOUNGER: 'years younger',
  AREA: 'Area',
  CONDITION: 'Condition',
  OVERLAPS: 'Overlaps',
  INDEX_OVERLAPS: 'Index overlaps',
  CARDIOVASCULAR: 'Cardiovascular',
  CARDIOVASCULAR_HEALTH: 'Cardiovascular health',
  METABOLIC: 'Metabolic',
  METABOLIC_HEALTH: 'Metabolic health',
  AUTOIMMUNE: 'Autoimmune',
  AUTOIMMUNE_HEALTH: 'Autoimmune health',
  RESPIRATORY: 'Respiratory',
  RESPIRATORY_HEALTH: 'Respiratory health',
  FEMALE: 'Female',
  FEMALE_HEALTH: 'Female health',
  RISK_OF_HYPER: 'Inc. risk of hypertension',
  PRE_HYPERTENSION: 'Pre-hypertension',
  HYPERTENSION: 'Hypertension',
  MI_CVA: 'MI & CVA',
  ATHEROSCLEROSIS: 'Atherosclerosis',
  CORONARY: 'Coronary artery disease',
  TYPE_2_DIABETES: 'Type 2 diabetes',
  DYSLIPIDEMIA: 'Dyslipidemia',
  RHEUMATOID: 'Rheumatoid arthritis',
  ULCERATIVE_COLITIS: 'Ulcerative colitis',
  CROHN: "Crohn's disease",
  SLE: 'SLE',
  COPD: 'COPD',
  PERIMENOPAUSE: 'Perimenopause',
  NO_SIGNIFICANT_OVERLAP: 'No significant overlap',
  SIGNIFICANT_OVERLAP: 'Significant overlap',
  NO_SIGNIFICANT_AREAS: 'No significant areas for attention',
  SOME_AREAS: 'Some areas for attention',
  SIGNIFICANT_AREAS: 'Significant areas for attention',
  SLIGHTLY_OUT_OF_RANGE: 'Slightly out of range',
  SIGNIFICANTLY_OUT_OF_RANGE: 'Significantly out of range',
  AREAS_FOR_ATTENTION: 'Areas for attention',
  PLEASE_NOTE: 'Please note',
  PLEASE_NOTE_SENTENCE: 'While certain patterns may show similarities to those observed in specific conditions, this does not confirm the presence of a disease or any of its subclinical forms.',
};

export let polish = {
  BIOLOGICAL_AGE: 'Wiek biologiczny',
  CHRONOLOGICAL_AGE: 'Wiek Kalendarzowy',
  GLYCAN: 'Glikan',
  PEAK: 'Pik',
  LOWER_THAN_AVERAGE: 'niższy od wartości średniej',
  AROUND_AVERAGE: 'W okolicach wartości średniej',
  HIGHER_THAN_AVERAGE: 'wyższy od wartości średniej',
  SOME_OVERLAP_LONG: 'Znaczny stopień pokrywania się',
  MINOR_OVERLAP_LONG: 'Nieznaczne stopień pokrywania się',
  NO_OVERLAP_LONG: 'Brak znaczącego pokrywania się',
  SOME_OVERLAP: 'Częściowy',
  MINOR_OVERLAP: 'Niewielki',
  NO_OVERLAP: 'Brak',
  OVERLAP_TEXT: 'indeksów glikanowych między pacjentem a badanymi z tym schorzeniem.',
  SYMPTOMS: 'Sygnały i objawy',
  SYMPTOM_ONE: 'Przeważnie przebiega w sposób bezobjawowy',
  SYMPTOM_TWO: 'Ciśnienie tętnicze stale >140/90 mmHg',
  SYMPTOM_THREE: 'Objawy nadciśnienia złośliwego (ból głowy, zawroty głowy, duszność itp.)',
  SYMPTOM_FOUR: 'Objawy choroby wieńcowej (np. samoistnie ustępujący ból w klatce piersiowej, bezdech)',
  SYMPTOM_FIVE: 'Objawy choroby tętnic obwodowych (np. ból nóg podczas aktywności)',
  SYMPTOM_SIX: 'Samoograniczający się ból w klatce piersiowej ± promieniujący do szczęki/lewego ramienia/pleców',
  SYMPTOM_SEVEN: 'Duszność',
  SYMPTOM_EIGHT: 'Inne (omdlenia, kołatanie serca, obrzęk nóg, orhhopnoe itp.)',
  SYMPTOM_NINE: 'Ból brzucha i skurcze',
  SYMPTOM_TEN: 'Nawracająca biegunka (± krew)',
  SYMPTOM_TEN_B: 'Nagła potrzeba wypróżnienia',
  SYMPTOM_ELEVEN: 'Utrata masy ciała',
  SYMPTOM_TWELVE: 'Ogólnoustrojowe (np. zmęczenie, utrata masy ciała, owrzodzenia jamy ustnej, wysypka w kształcie motyla w okolicy policzków i nosa)',
  SYMPTOM_THIRTEEN: 'Narządowe (ból w klatce piersiowej, trudności w oddychaniu, obrzęk nóg, niedokrwistość itp.)',
  SYMPTOM_FOURTEEN: 'Ból i obrzęk stawów',
  SYMPTOM_FIFTEEN: 'Zmęczenie',
  SYMPTOM_SIXTEEN: 'Zwiększone pragnienie i częste oddawanie moczu',
  SYMPTOM_SEVENTEEN: 'Powolne gojenie się ran, niewyraźne widzenie, częste pleśniawki',
  SYMPTOM_EIGHTEEN: 'Trudności w oddychaniu',
  SYMPTOM_NINETEEN: 'Przewlekły kaszel (± produktywny)',
  SYMPTOM_TWENTY: 'Nieregularny cykl menstruacyjny',
  SYMPTOM_TWENTYONE: 'Objawy naczynioruchowe (np. uderzenia gorąca)',
  SYMPTOM_TWENTYTWO: 'Inne (np. wahania nastroju, trudności poznawcze, zaburzenia snu)',
  SYMPTOM_TWENTYTHREE: 'Ból stawów, obrzęk, sztywność i rumień',
  SYMPTOM_TWENTYFOUR: 'Zajęcie mniejszych stawów dystalnych (palce rąk i nóg), zwykle symetryczne',
  SYMPTOM_TWENTYFIVE: 'Ogólnoustrojowe (zmęczenie, utrata masy ciała itp.)',
  POSSIBLE_FOLLOW_UP: 'Ewentualne dalsze działania',
  POSSIBLE_FOLLOW_UP_ONE: 'Seryjne pomiary ciśnienia tętniczego i/lub 24-godzinne monitorowanie ciśnienia tętniczego',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI i/lub kontrola składu ciała',
  POSSIBLE_FOLLOW_UP_THREE: 'Podstawowe badania krwi (profil lipidowy, czynność nerek i wątroby)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Badania krwi: podstawowy i rozszerzony profil lipidowy (np. Lp(a), ApoB), hsCRP, homocysteina, czynność nerek i wątroby, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'Kontrola ciśnienia tętniczego',
  POSSIBLE_FOLLOW_UP_SIX: 'EKG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Skierowanie do kardiologa na inne badania (np. echo serca, TK naczyń wieńcowych)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Skierowanie do kardiologa na inne badania (np. wskaźnik uwapnienia tętnic wieńcowych)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Skierowanie do kardiologa na inne badania (np. echokardiogram wysiłkowy)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Badania kału: test na obecność krwi utajonej (FIT), kalprotektyna w kale',
  POSSIBLE_FOLLOW_UP_TEN: 'Skierowanie na kolonoskopię, TK',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, CRP, OB, autoprzeciwciała (np. ANA, w tym anty-dsDNA).',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Badanie ogólne moczu',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Badania obrazowe ukierunkowane na narządy (np. TK klatki piersiowej, TK jamy brzusznej)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, stężenie glukozy i insuliny na czczo, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Badania profilu lipidowego krwi: podstawowe i rozszerzone (np. oxLDL, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Inne badania krwi hsCRP, homocysteina, czynność nerek i wątroby, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Badania krwi: pełna morfologia krwi',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometria',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'EKG, RTG klatki piersiowej',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Badania krwi (w tym FSH, estradiol, progesteron, testosteron, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Skierowanie do specjalisty/ginekologa zajmującego się (peri)menopauzą',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Badania krwi: pełna morfologia krwi, czynnik reumatoidalny, przeciwciała anty-CCP, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Obrazowanie stawów (zdjęcia rentgenowskie, rezonans magnetyczny)',
  PERCENTILE: 'percentylu',
  SINGLE_PERCENTILE: 'percentyl',
  RISK_FACTORS: 'Czynniki ryzyka',
  RISK_FACTOR_ONE: 'Historia chorób (np. zespół kardiometaboliczny, choroby autoimmunologiczne)',
  RISK_FACTOR_TWO: 'Historia przyjmowania leków (np. statyn, leków przeciwzakrzepowych)',
  RISK_FACTOR_THREE: 'Palenie tytoniu',
  RANKS_YOU: 'Twoj wynik klasyfikuje Cię w',
  RELATED_RESEARCH_PAPERS: 'Publikacje naukowe',
  YOUR_RESULT: 'Twój wynik',
  CHRONIC_INFLAMMATION: 'TempText POLISH1',
  ANTI_INFLAMMATORY: 'TempText POLISH2',
  PRO_INFLAMMATORY: 'TempText POLISH3',
  SUPPORTIVE_INDEX: 'TempText POLISH4',
  GLYCAN_SHIELD: 'TempText Shield (S)',
  GLYCAN_YOUTH: 'TempText Youth (G2)',
  GLYCAN_MATURE: 'TempText Mature (G0)',
  GLYCAN_MEDIAN: 'TempText Median (G1)',
  GLYCAN_LIFESTYLE: 'TempText Lifestyle (B)',
  WORSE: 'TempText Worse',
  BETTER: 'TempText Better',
  AVERAGE: 'TempText Average',
};

export let slovenian = {
  BIOLOGICAL_AGE: 'Biološka starost',
  CHRONOLOGICAL_AGE: 'Kronološka starost',
  CHRONOLOGICAL_AGE_TWO: 'kronološke starosti',
  RANKS_YOU: 'Ta rezultat vas uvršča med',
  PERCENTILE: 'percentilov',
  SINGLE_PERCENTILE: 'percentil',
  YOUR_RESULT: 'Vaš rezultat',
  GLYCAN_SHIELD: 'Glikanski ščit (S)',
  GLYCAN_YOUTH: 'Mladost glikanov (G2)',
  GLYCAN_MATURE: 'Zrelost glikanov (G0)',
  GLYCAN_MEDIAN: 'Povprečje glikanov (G1)',
  GLYCAN_LIFESTYLE: 'Življenjski slog glikanov (B)',
  GLYCAN_LIFESTYLE_B: 'Življenjski slog glikanov (B)',
  CHRONIC_INFLAMMATION: 'Kronično vnetje',
  ANTI_INFLAMMATORY: 'Protivnetni',
  ANTI_INFLAMMATORY_INDEX: 'Protivnetni index',
  PRO_INFLAMMATORY: 'Pro-vnetni',
  PRO_INFLAMMATORY_INDEX: 'Pro-vnetni index',
  SUPPORTIVE_INDEX: 'Podporni kazalnik',
  WORSE: 'Slabše',
  BETTER: 'Boljše',
  OPTIMAL: 'Optimalen',
  SUBOPTIMAL: 'neoptimalno',
  AVERAGE: 'Povprečje',
  AROUND_AVERAGE: 'Približno povprečje',
  THIS_RESULT_RANKS_IN_THE: 'Ta rezultat se uvršča med',
  INDEX_SCORE: 'Rezultat kazalnika',
  MEASURED_RESULT: 'Vaš rezultat',
  POPULATION_AVERAGE: 'Povprečje prebivalstva',
  AGE: 'Dob',
  SAME_AS: 'Enako kot',
  THAN: 'od',
  YEAR_OLDER: 'starejši',
  YEARS_OLDER: 'starejši',
  YEAR_YOUNGER: 'let mlajši',
  YEARS_YOUNGER: 'let mlajši'
};

export let japanese = {
  BIOLOGICAL_AGE: '生物学的年齢',
  CHRONOLOGICAL_AGE: '暦年齢',
  CHRONOLOGICAL_AGE_TWO: '暦年齢',
  SI_SCORE: 'SI score',
  GLYCAN: 'Glycan',
  PEAK: 'Peak',
  LOWER_THAN_AVERAGE: 'Lower than average',
  BELOW_AVERAGE: 'Below average',
  AROUND_AVERAGE: '平均値くらい',
  HIGHER_THAN_AVERAGE: 'Higher than average',
  ABOVE_AVERAGE: 'Above average',
  SOME_OVERLAP_LONG: 'Some overlap',
  MINOR_OVERLAP_LONG: 'Minor overlap',
  NO_OVERLAP_LONG: 'No significant overlap',
  SOME_OVERLAP: 'Some overlap',
  MINOR_OVERLAP: 'Minor overlap',
  NO_OVERLAP: 'No significant overlap',
  OVERLAP_TEXT: 'of glycan indexes between your patient and this condition.',
  SYMPTOMS: 'Signs and symptoms',
  SYMPTOM_ONE: 'Usually asymptomatic',
  SYMPTOM_TWO: 'BP consistently >140/90 mmHg',
  SYMPTOM_THREE: 'Signs of malignant hypertension (headache, dizziness, breathlessness, etc.)',
  SYMPTOM_FOUR: 'Signs of coronary artery disease (e.g., self-resolving chest pain, breathlessness)',
  SYMPTOM_FIVE: 'Signs of peripheral artery disease (e.g., leg pain during activity)',
  SYMPTOM_SIX: 'Self-limiting chest pain ± radiation into jaw/left arm/back',
  SYMPTOM_SEVEN: 'Breathlessness',
  SYMPTOM_EIGHT: 'Other (syncope, palpitations, leg edema, orthopnea, etc.)',
  SYMPTOM_NINE: 'Abdominal pain and cramping/left arm/back',
  SYMPTOM_TEN: 'Recurring diarrhea (± blood)',
  SYMPTOM_TEN_B: 'Urgency to defecate',
  SYMPTOM_ELEVEN: 'Weight loss',
  SYMPTOM_TWELVE: 'Systemic (e.g., fatigue, weight loss, mouth ulcers, butterfly skin rash)',
  SYMPTOM_THIRTEEN: 'Organ-specific (chest pain, difficulty breathing, leg swelling, anaemia, etc.)',
  SYMPTOM_FOURTEEN: 'Joint pain and swelling',
  SYMPTOM_FIFTEEN: 'Fatigue',
  SYMPTOM_SIXTEEN: 'Increased thirst and frequent urination',
  SYMPTOM_SEVENTEEN: 'Slow wound healing, blurred vision, frequent thrush',
  SYMPTOM_EIGHTEEN: 'Difficulty breathing',
  SYMPTOM_NINETEEN: 'Chronic cough (± productive)',
  SYMPTOM_TWENTY: 'Irregular menstrual cycle',
  SYMPTOM_TWENTYONE: 'Vasomotor symptoms (e.g., hot flushes, night sweats)',
  SYMPTOM_TWENTYTWO: 'Other (e.g., mood swings, cognitive difficulties, sleep disturbance)',
  SYMPTOM_TWENTYTHREE: 'Joint pain, swelling, stiffness and erythema',
  SYMPTOM_TWENTYFOUR: 'Smaller and distant joint involvement (fingers, toes), usually symmetrical',
  SYMPTOM_TWENTYFIVE: 'Systemic (fatigue, weight loss, etc.)',
  POSSIBLE_FOLLOW_UP: 'Possible follow-up',
  POSSIBLE_FOLLOW_UP_ONE: 'Serial blood pressure (BP) measurements Â± 24-hour BP monitoring',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI and/or body composition check',
  POSSIBLE_FOLLOW_UP_THREE: 'Basic bloods (lipid profile, renal and liver function)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Blood tests: basic and extended lipid profile (e.g., Lp(a), ApoB), hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'BP check',
  POSSIBLE_FOLLOW_UP_SIX: 'ECG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Cardiology referral for other tests (e.g., cardiac echo, coronary CT)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Cardiology referral for other tests (e.g., coronary artery calcium score)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Cardiology referral for other tests (e.g., stress echocardiogram)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Blood tests: full blood count, renal and liver function, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Stool tests: faecal immunochemical test (FIT), faecal calprotectin',
  POSSIBLE_FOLLOW_UP_TEN: 'Referral for CT colonoscopy',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Blood tests: full blood count, renal and liver function, CRP, ESR, autoantibodies (e.g., ANA, anti-dsDNA)',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Urinalysis',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Organ-targeted imaging (e.g., CT thorax, CT abdomen)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Blood tests: full blood count, renal and liver function, fasting glucose and insulin, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Lipid profile blood tests: basic and extended (incl. oxLDL, VLDL, LDL-P, Lp-PLA2, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Other blood tests hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Blood tests: full blood count',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometry',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'ECG, chest X-ray',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Blood tests (incl. FSH, oestradiol, progesterone, testosterone, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Referral to (peri)menopause specialist/gynaecologist',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Blood tests: full blood count, rheumatoid factor, anti-CCP antibodies, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Joint imaging (X-rays, MRI)',
  PERCENTILE: 'パーセンタイル',
  SINGLE_PERCENTILE: 'パーセンタイル',
  RISK_FACTORS: 'Risk factors',
  RISK_FACTOR_ONE: 'Past medical history (cardiometabolic syndrome, autoimmune disease)',
  RISK_FACTOR_TWO: 'Medication history (e.g., statins, blood thinners)',
  RISK_FACTOR_THREE: 'Current/previous smoking history',
  RANKS_YOU: 'この結果により、あなたは',
  THIS_RESULT_RANKS_IN_THE: 'この結果は、',
  RELATED_RESEARCH_PAPERS: 'Related research papers',
  YOUR_RESULT: 'Your result',
  CHRONIC_INFLAMMATION: '慢性炎症',
  SYSTEMIC_INFLAMMATION: '全身性炎症',
  ANTI_INFLAMMATORY: '抗炎症性',
  ANTI_INFLAMMATORY_INDEX: '抗炎症性',
  PRO_INFLAMMATORY: '炎症誘発性',
  PRO_INFLAMMATORY_INDEX: '炎症誘発性',
  SUPPORTIVE_INDEX: 'サポート指標',
  GLYCAN_SHIELD: 'Glycan Shield (S)',
  GLYCAN_YOUTH: 'Glycan Youth (G2)',
  GLYCAN_MATURE: 'Glycan Mature (G0)',
  GLYCAN_MEDIAN: 'Glycan Median (G1)',
  GLYCAN_LIFESTYLE: 'Glycan Lifestyle (B)',
  GLYCAN_LIFESTYLE_B: 'Glycan Bisection (B)',
  WORSE: 'より年上',
  BETTER: 'より若い',
  OPTIMAL: '最適な',
  SUBOPTIMAL: '最適ではない',
  AVERAGE: '平均値',
  INDEX_SCORE: '指標スコア',
  MEASURED_RESULT: 'あなたの結果',
  POPULATION_AVERAGE: '母集団平均',
  AGE: '年齢',
  SAME_AS: '〜と同じ',
  THAN: 'より',
  YEAR_OLDER: '年上',
  YEARS_OLDER: '年上',
  YEAR_YOUNGER: '年下',
  YEARS_YOUNGER: '年下',
};

export let chinese = {
  PRIMARY_FOCUS: '主要焦点 — 基于主要指标',
  FURTHER_TESTING: '进一步检测',
  SECONDARY_FOCUS: '次要焦点 — 基于二级索引',
  PRIMARY_TITLE_1: '维持并保护当前的炎症调控与免疫老化进程',
  PRIMARY_DESC_1: '评估这些最佳结果是否由于药物干预（如激素替代疗法 HRT、睾酮替代疗法 TRT、甲状腺素、胰增素疗法如 GLP-1 激动剂、抗炎药）、有利的遗传特征（如与长寿相关或有益于糖链的变异），或受生活方式因素所影响。若存在风险因素或慢性疾病，此结果表明当前的策略已成功控制炎症',
  PRIMARY_FURTHER_1: '除非出现新的症状，否则无需进行除年度常规预防性实验室检查以外的额外检测。',
  PRIMARY_TITLE_2: '避免低度炎症诱因，以防止免疫系统进一步老化',
  PRIMARY_DESC_2: '为减轻持续的免疫激活，应评估可能的诱因，例如近期发生或未完全消除的感染。可重点在于减少促炎性食物、纠正能量失衡以及限制酒精摄入。加强规律睡眠模式，并优化有利于压力调节与缓解的策略。',
  PRIMARY_FURTHER_2: '考虑检测高敏C反应蛋白（hs-CRP）及其他炎症标志物、25-羟维生素D、铁蛋白以及铁代谢相关检查。评估血脂各指标及空腹血糖–胰岛素水平，以判断心脏代谢负荷。',
  PRIMARY_TITLE_3: '优化运动锻炼以支持免疫系统的年轻化',
  PRIMARY_DESC_3: '鼓励采用平衡的训练方式，避免过度的高强度有氧运动，引入并保持力量训练。同时，重视恢复策略，以支持免疫系统的长期年轻化。若存在个人或家族自身免疫性疾病史，应密切监测青年糖链指数（Glycan Youth）的变化趋势，因为维持该指标对遗传易感个体可能尤为重要。',
  PRIMARY_FURTHER_3: '若存在个人或家族自身免疫或炎症性疾病史，应评估红细胞沉降率（ESR）、高敏C反应蛋白（hs-CRP）、抗核抗体筛查（ANA）、以及甲状腺基础功能（TSH、fT4、fT3）。同时监测维生素D水平。',
  PRIMARY_TITLE_4: '通过胃肠道健康、营养与运动支持降低炎症',
  PRIMARY_DESC_4: '重点改善肠道健康，可使用针对性的益生菌、益生元以及增加膳食纤维的多样性；通过全谷物食物的抗炎成分提升饮食的营养支持；必要时评估微量营养素缺乏情况；同时通过增强体能来提升整体免疫适应力。',
  PRIMARY_FURTHER_4: '可考虑进行微量营养素评估（Omega-3 指数、锌、镁、维生素D、维生素B12、叶酸）、高敏C反应蛋白（hs-CRP）检测，以及在临床怀疑时进行针对性肠道健康评估（粪便分析、微生物组检测或肠道渗透性指标）。',
  PRIMARY_TITLE_5: '系统恢复策略以平衡高压力生活方式',
  PRIMARY_DESC_5: '帮助客户建立可行的休息规律，加强压力调节策略，并使日常习惯与昼夜节律保持一致。对于处于高压环境中的个体，实施切实可行的恢复方法，例如安排固定的放松时间、呼吸训练或短暂的活动间歇，以减轻持续负荷对免疫系统的影响。监测心脏代谢健康指标，并及时处理任何早期失衡指标，以防止免疫系统进一步受压，导致老化。',
  PRIMARY_FURTHER_5: '评估血脂各指标、高敏C反应蛋白（hs-CRP）、25-羟维生素D、空腹血糖–胰岛素、抗核抗体筛查（ANA）。可考虑评估睡眠质量与心率/心律变异性（HRV），用于恢复监测。',
  PRIMARY_TITLE_6: '通过针对性地调整生活方式以增强血管韧性',
  PRIMARY_DESC_6: '建议采用以富含 ω-3 脂肪酸来源、含硝酸盐的蔬菜（常见于多种绿叶蔬菜）和富含多酚的食物为主的饮食模式。同时，限制深加工食品、减少钠和糖的摄入。建议客户进行规律的中等强度有氧运动，并能有效地恢复和良好睡眠习惯。监测心血管健康，尤其是在有个人或家族心血管疾病史的情况下。',
  PRIMARY_FURTHER_6: "检查血脂各指标、血压（包括波动性）、高敏 C 反应蛋白（hs-CRP）以及空腹血糖–胰岛素。可考虑检测 Omega-3 指数和同型半胱氨酸，以支持心血管健康方案制定。",
  PRIMARY_TITLE_7: '通过体能恢复、生活节律和核心营养系统来改善免疫反应能力',
  PRIMARY_DESC_7: '建议构建并实施有效放松程序和固定的就寝时间以稳定昼夜节律，结合主动恢复策略，并通过增加膳食纤维多样性、十字花科蔬菜以及已被证实能增强免疫系统调节的营养成分来支持肠道和肝脏健康。',
  PRIMARY_FURTHER_7: '微量营养素谱（锌、镁、维生素 D、B12、叶酸、Omega-3 指数）、高敏 C 反应蛋白（hs-CRP）、空腹血糖–胰岛素。如症状持续，应评估性激素和甲状腺功能，以观察它们对系统恢复的影响。',
  PRIMARY_TITLE_8: '通过有针对性的全系统干预延缓早期免疫老化',
  PRIMARY_DESC_8: '建议在营养方面进行结构化改善（如抗炎、营养密集且能量平衡稳定的膳食），增加包括有氧和阻力训练在内的身体活动，强化规律且高质量的睡眠，并实施日常的压力恢复实践。此类模式可能提示早期代谢负担，因此需要更有针对性和全面的干预来恢复免疫韧性。',
  PRIMARY_FURTHER_8: '完整的心脏代谢指标（血脂、血糖–胰岛素、高敏 C 反应蛋白）、维生素 D 及部分微量营养素检测、抗核抗体（ANA）筛查。如生活方式负荷持续存在，应考虑基线激素评估。',
  PRIMARY_TITLE_9: '降低慢性炎症负担以减缓生物学衰老',
  PRIMARY_DESC_9: '优先通过抗炎、平衡代谢的饮食来降低炎症水平，处理胰岛素抵抗、血脂异常或激素失衡等核心驱动因素，并实施日常的压力调节策略。',
  PRIMARY_FURTHER_9: '评估血压、血糖控制、血脂各指标、激素状态以及全身炎症指标，以指导有针对性的干预。',
  PRIMARY_TITLE_10: '通过针对核心代谢与调节系统来恢复免疫适应性',
  PRIMARY_DESC_10: '改善身体成分，稳定昼夜节律，并优化能量摄入。建议采取均衡的训练方式，限制过量有氧运动，引入或保持力量训练，并优先考虑体能恢复策略。如果有个人或家族自身免疫疾病史，应密切监测 青年糖链变化 趋势。',
  PRIMARY_FURTHER_10: '可考虑评估代谢指标、性激素水平以及自身免疫相关指标，以发现潜在的炎症驱动因素。',
  PRIMARY_TITLE_11: '通过恢复肠道–营养–压力轴来降低炎症水平',
  PRIMARY_DESC_11: '通过增加膳食纤维多样性、发酵食物，并在必要时进行消化功能评估来支持肠道完整性；优化微量营养素和糖链支撑元素（如锌、镁、Omega-3、维生素 D）；并通过规律的恢复习惯和昼夜节律协调来减少累积性压力。',
  PRIMARY_FURTHER_11: '可考虑评估消化功能、全身炎症水平和性激素平衡，以识别并纠正免疫消退的潜在障碍。',
  PRIMARY_TITLE_12: '通过针对代谢与免疫过度来逆转慢性炎症',
  PRIMARY_DESC_12: '建议实施结构化的抗炎方案，重点改善代谢健康、优化营养成分、稳定血糖，并减少饮食及生活方式引发的炎症因素。',
  PRIMARY_FURTHER_12: '评估血压、血脂状态、性激素平衡及全身炎症水平，以识别关键驱动因素并实施有针对性的干预，从而逆转免疫老化轨迹。',
  PRIMARY_TITLE_13: '通过减少炎症诱发因素并增强体能恢复来降低免疫负荷',
  PRIMARY_DESC_13: '重点改善肠道健康，限制饮食和环境毒素接触，并避免深加工食品及促炎食物。',
  PRIMARY_FURTHER_13: '评估血压、血糖控制、血脂指标、性激素状态及全身炎症水平，以指导有针对性的干预，保护长期免疫韧性并预防免疫老化。',
  PRIMARY_TITLE_14: '通过重建主要调节能力支持免疫恢复',
  PRIMARY_DESC_14: '重点改善身体主要营养成分，同时避免过度训练，强调运动质量和充分恢复，通过规律的作息稳定昼夜节律，实现多样化、抗炎饮食管理能量状态。',
  PRIMARY_FURTHER_14: '评估代谢指标、激素水平及自身免疫风险，以发现并解决免疫老化的深层驱动因素。',
  PRIMARY_TITLE_15: '通过平衡压力、运动与恢复重建免疫年轻状态',
  PRIMARY_DESC_15: '通过规律的作息时间、中等强度且均衡的身体锻炼，以及构建休息程序来支持体能恢复。确保充足营养，并优化每日能量摄入。',
  PRIMARY_FURTHER_15: '评估代谢指标、甲状腺功能、激素水平及自身免疫风险，以发现并解决免疫老化的深层驱动因素。',
  PRIMARY_TITLE_16: '通过支持肠道完整性并减少免疫刺激物来强化免疫调节',
  PRIMARY_DESC_16: '通过增加膳食纤维多样性和支持微生物组的策略改善肠道健康，支持解毒与排泄途径，并减少常见免疫刺激物的接触，如酒精、食物敏感原及环境毒素等。',
  PRIMARY_FURTHER_16: '可在适当情况下评估消化指标（如微生物组分析、Zonulin）、全身炎症水平、关键微量营养素、性激素平衡及自身抗体。',
  PRIMARY_TITLE_17: '通过支持肠–肝轴与营养充足性改善免疫能力恢复',
  PRIMARY_DESC_17: '通过富含膳食纤维的抗炎食物及必要的针对性支持增强肠道和肝脏功能，强化系统性恢复习惯，并确保关键微量营养素及糖链构建营养素的充足摄入。',
  PRIMARY_FURTHER_17: '可考虑评估铁状态、维生素 B12、叶酸、维生素 D、锌、镁及消化功能（如微生物组分析、粪便标志物、Zonulin）；如存在自身免疫风险，可筛查自身抗体。',
  PRIMARY_TITLE_18: '通过系统性生活方式与环境干预降低炎症水平',
  PRIMARY_DESC_18: '建议采取高营养的抗炎饮食；恢复睡眠–觉醒节律；强化日常压力调节；引入规律的中等强度身体锻炼；并优先改善营养成分以降低代谢负担。为减轻累积免疫负荷，应减少环境接触，如酒精、内分泌干扰物和污染物。',
  PRIMARY_FURTHER_18: '评估心脏代谢指标、激素平衡、全身炎症水平，并在适当情况下进行自身免疫相关检测。',
  PRIMARY_TITLE_19: '通过平衡压力、运动与营养重建免疫韧性',
  PRIMARY_DESC_19: '通过规律的睡眠–觉醒周期和构建休息，支持深度恢复，并帮助找到身体活动与恢复之间的适当平衡，避免过度或不足训练。优化宏量和微量营养素摄入，尤其是蛋白质、矿物质及抗炎成分，并评估甲状腺功能、皮质醇节律、胰岛素敏感性、营养组份和睡眠质量，以识别免疫衰退的关键因素。',
  PRIMARY_FURTHER_19: '全血计数（CBC）、肝/肾功能、炎症指标、血糖–胰岛素谱、完整的甲状腺和肾上腺评估、维生素 D、肠道功能（粪便分析、微生物组、呼气试验）、毒素筛查及自身免疫指标（如适用）。功能性指标如心率变异性（HRV）、最大摄氧量（VO₂max）及身体成分也可用于追踪恢复状况。',
  PRIMARY_TITLE_20: '通过支持肠道健康与恢复表征，恢复免疫能力',
  PRIMARY_DESC_20: '通过增加膳食纤维多样性和支持微生物组的策略促进肠道修复，减少深加工食品、酒精及避免环境毒素等免疫刺激物，并通过规律睡眠、轻度运动和结构化压力调节程序强化身体的恢复能力。',
  PRIMARY_FURTHER_20: '可考虑评估肠道通透性或微生物组平衡、营养吸收情况（锌、镁、B 族维生素）、皮质醇节律及其他屏障功能异常的指标。',
  PRIMARY_TITLE_21: '通过恢复昼夜节律与激素调节重建免疫平衡',
  PRIMARY_DESC_21: '建议进行全面健康评估以查清潜在炎症驱动因素。优先实现昼夜节律的同步，通过规律的睡眠–觉醒时间来维持，同时在工作日整合简短但规律的恢复活动（如短时散步、呼吸练习、运动休息），避免过度依赖高强度运动，强调平衡的力量与灵活性训练。处理免疫紊乱的核心诱发因素，如高血压、胰岛素抵抗、血脂异常或激素失衡。',
  PRIMARY_FURTHER_21: '全血计数（CBC）、肝肾功能、血脂谱、血糖–胰岛素谱、完整的甲状腺、肾上腺及性激素评估、炎症指标（包括高敏 C 反应蛋白）、维生素 D、铁状态、维生素 B12、叶酸、镁、锌、同型半胱氨酸、Omega-3 指数、肠道功能检测（粪便分析、微生物组、呼气试验）、以及在适用情况下的自身免疫指标。功能性指标如心率变异性（HRV）、最大摄氧量（VO₂max）和身体成分也可用于追踪恢复状况。',
  PRIMARY_TITLE_22: '降低全身炎症负荷并保护心血管健康',
  PRIMARY_DESC_22: '建议进行全面健康评估以查明潜在驱动因素。实施抗炎、营养丰富的饮食，并关注口腔和肠道健康，以消除潜在的持续免疫激活源。通过规律的中等强度运动、压力调节和优化睡眠来强化心血管支持。',
  PRIMARY_FURTHER_22: '全血计数（CBC）、肝肾功能、血脂谱、血糖–胰岛素谱、完整的甲状腺、肾上腺及性激素评估、炎症指标（包括高敏 C 反应蛋白）、维生素 D、铁状态、维生素 B12、叶酸、镁、锌、同型半胱氨酸、Omega-3 指数、肠道功能检测（粪便分析、微生物组、呼气试验）、以及在适用情况下的自身免疫指标。功能性指标如心率变异性（HRV）、最大摄氧量（VO₂max）和身体成分也可用于追踪恢复状况。',
  PRIMARY_TITLE_23: '通过恢复与韧性重建免疫适应性',
  PRIMARY_DESC_23: '建议进行全面健康评估以查明潜在驱动因素。重点通过多样化、富含蛋白质和微量营养素的饮食补充营养，支持消化健康以优化吸收，并通过规律睡眠、压力调节以及温和、渐进的身体活动实施结构化恢复。',
  PRIMARY_FURTHER_23: '全血计数（CBC）、肝肾功能、血脂谱、血糖–胰岛素谱、完整的甲状腺、肾上腺及性激素评估、炎症指标（包括高敏 C 反应蛋白）、维生素 D、铁状态、维生素 B12、叶酸、镁、锌、同型半胱氨酸、Omega-3 指数、肠道功能检测（粪便分析、微生物组、呼气试验）、以及在适用情况下的自身免疫指标。功能性指标如心率变异性（HRV）、最大摄氧量（VO₂max）和身体成分也可用于追踪恢复状况。',
  PRIMARY_TITLE_24: '解决系统性免疫激发与慢性炎症的根本驱动因素',
  PRIMARY_DESC_24: '建议进行全面健康评估以查明潜在驱动因素。重点在于去除炎症诱因（来自饮食、环境及肠道）、重建恢复能力（通过睡眠、营养及压力调节）以及恢复代谢和激素平衡。',
  PRIMARY_FURTHER_24: '全血计数（CBC）、肝肾功能、血脂谱、血糖–胰岛素谱、完整的甲状腺、肾上腺及性激素评估、炎症指标（包括高敏 C 反应蛋白）、维生素 D、铁状态、维生素 B12、叶酸、镁、锌、同型半胱氨酸、Omega-3 指数、肠道功能检测（粪便分析、微生物组、呼气试验）、以及在适用情况下的自身免疫指标。功能性指标如心率变异性（HRV）、最大摄氧量（VO₂max）和身体成分也可用于追踪恢复状况。',
  PRIMARY_TITLE_25: '解决系统性免疫负荷与慢性炎症的根本驱动因素',
  PRIMARY_DESC_25: '建议进行全面健康评估以查明潜在驱动因素。评估并处理肠道/屏障功能异常、内分泌失衡、毒素接触及慢性压力；在强化睡眠、针对性营养及压力调节的同时，减少饮食和环境中的炎症诱因，以重建免疫消退能力。',
  PRIMARY_FURTHER_25: '全血计数（CBC）、肝肾功能、血脂谱、血糖–胰岛素谱、完整的甲状腺、肾上腺及性激素评估、炎症指标（包括高敏 C 反应蛋白）、维生素 D、铁状态、维生素 B12、叶酸、镁、锌、同型半胱氨酸、Omega-3 指数、肠道功能检测（粪便分析、微生物组、呼气试验）、以及在适用情况下的自身免疫指标。功能性指标如心率变异性（HRV）、最大摄氧量（VO₂max）和身体成分也可用于追踪恢复状况。',
  PRIMARY_TITLE_26: '通过体能恢复与韧性重建免疫适应性',
  PRIMARY_DESC_26: '建议进行全面健康评估以查明潜在驱动因素。重点通过多样化、富含蛋白质和微量营养素的饮食补充营养储备，支持消化健康以优化吸收，并通过规律睡眠、压力调节以及温和、渐进的身体活动实施整体恢复。同时努力恢复代谢和激素平衡。',
  PRIMARY_FURTHER_26: '全血计数（CBC）、肝肾功能、血脂谱、血糖–胰岛素谱、完整的甲状腺、肾上腺及性激素评估、炎症指标（包括高敏 C 反应蛋白）、维生素 D、铁状态、维生素 B12、叶酸、镁、锌、同型半胱氨酸、Omega-3 指数、肠道功能检测（粪便分析、微生物组、呼气试验）、以及在适用情况下的自身免疫指标。功能性指标如心率变异性（HRV）、最大摄氧量（VO₂max）和身体成分也可用于追踪恢复状况。',
  PRIMARY_TITLE_27: '降低炎症负荷并恢复免疫系统的韧性',
  PRIMARY_DESC_27: '建议进行全面健康评估以查明潜在驱动因素。重点在于去除炎症诱因（来自饮食、环境及肠道）、重建恢复能力（通过睡眠、营养及压力调节）以及恢复代谢和激素平衡。',
  PRIMARY_FURTHER_27: '全血计数（CBC）、肝肾功能、血脂谱、血糖–胰岛素谱、完整的甲状腺、肾上腺及性激素评估、炎症指标（包括高敏 C 反应蛋白）、维生素 D、铁状态、维生素 B12、叶酸、镁、锌、同型半胱氨酸、Omega-3 指数、肠道功能检测（粪便分析、微生物组、呼气试验）、以及在适用情况下的自身免疫指标。功能性指标如心率变异性（HRV）、最大摄氧量（VO₂max）和身体成分也可用于追踪恢复状况。',
  SUPPORTIVE_TITLE_1: '降低系统性与环境压力以稳定血管–呼吸韧性',
  SUPPORTIVE_DESC_1: '通过改善昼夜节律、执行系统性恢复程序，并尽量减少环境接触（如空气质量差、吸烟或职业刺激物）来应对植物神经压力。通过中等强度有氧锻炼支持心血管与呼吸健康，并定期监测血压和肺功能。',
  SUPPORTIVE_FURTHER_1: '血压评估（包括波动性）、肺功能测试、完整的心脏代谢指标面板。如存在风险因素或家族史，可考虑高级血管影像检查。在相关情况下，可进行睡眠研究以排查睡眠呼吸暂停，并使用心率变异性（HRV）或类似指标评估植物神经调节功能。',
  SUPPORTIVE_TITLE_2: '增强血管韧性并稳定植物神经神经功能',
  SUPPORTIVE_DESC_2: '保持规律的有氧与阻力训练，通过改善睡眠和压力调节提升恢复质量。尽量减少影响血管功能的因素，如过量饮酒、高钠饮食或未控制的血压。',
  SUPPORTIVE_FURTHER_2: '心血管筛查，包括血压监测（含波动性）、血脂分析、血糖–胰岛素检测。通过睡眠质量评估和心率变异性（HRV）追踪昼夜节律稳定性及恢复能力。如存在风险因素或家族史，可考虑高级血管影像检查。',
  SUPPORTIVE_TITLE_3: '应对血管脆弱性并监测早期疾病指标',
  SUPPORTIVE_DESC_3: '通过心脏保护型饮食、规律有氧运动以及维持最佳血压和血脂平衡来增强血管完整性。如有家族史，可考虑针对性筛查。',
  SUPPORTIVE_FURTHER_3: '血脂分析、血糖–胰岛素评估、高敏 C 反应蛋白（hsCRP）、以及在适用情况下的高级心血管风险筛查（如冠状动脉钙化评分或颈动脉内膜中层厚度）。如临床史或主要指标提示自身免疫特征，可考虑自身免疫面板检测。',
  SUPPORTIVE_TITLE_4: '降低环境压力负荷',
  SUPPORTIVE_DESC_4: '减少炎症触发因素，改善空气质量，管理压力，并优化身体营养成分。',
  SUPPORTIVE_FURTHER_4: '确认吸烟状况、血压波动、通过心率变异性（HRV）评估植物神经压力负荷、睡眠质量评估、环境毒素检查及身体成分分析。',
  SUPPORTIVE_TITLE_5: '维持平衡并进行监测',
  SUPPORTIVE_DESC_5: '回顾生活节律、营养充足性，以及细微的心血管或呼吸压力迹象。',
  SUPPORTIVE_FURTHER_5: '定期重新评估血压和心率变异性（HRV）以跟踪稳定性和植物神经功能状态。',
  SUPPORTIVE_TITLE_6: '支持血管稳定性',
  SUPPORTIVE_DESC_6: '维持心血管健康，并随时间监测变化趋势。',
  SUPPORTIVE_FURTHER_6: '常规间隔检查血压和血脂情况。',
  SUPPORTIVE_TITLE_7: '减少环境压力负荷',
  SUPPORTIVE_DESC_7: '避免接触读物、睡眠紊乱和呼吸负担。',
  SUPPORTIVE_FURTHER_7: '评估血压波动、HRV、睡眠质量及环境毒素暴露情况。',
  SUPPORTIVE_TITLE_8: '预防植物神经负担加剧',
  SUPPORTIVE_DESC_8: '鼓励一直支持昼夜节律、呼吸健康以及减压生活方式实践。如出现症状或主要指标出现不利变化，应进行随访。',
  SUPPORTIVE_FURTHER_8: '定期评估血压、HRV 和睡眠模式。',
  SUPPORTIVE_TITLE_9: '维持最佳支持指标平衡',
  SUPPORTIVE_DESC_9: '继续当前的预防策略，并进行定期监测。',
  SUPPORTIVE_FURTHER_9: '除非主要指标显示异常，否则无需额外检测。',
  BIOLOGICAL_AGE: '生物学年龄',
  CHRONOLOGICAL_AGE: '实际年龄',
  CHRONOLOGICAL_AGE_TWO: '实际年龄',
  SI_SCORE: 'SI 分值',
  GLYCAN: '糖链',
  PEAK: '峰',
  LOWER_THAN_AVERAGE: '低于平均数',
  BELOW_AVERAGE: '平均以下',
  AROUND_AVERAGE: '接近平均',
  HIGHER_THAN_AVERAGE: '高于平均数',
  ABOVE_AVERAGE: '平均以上',
  SOME_OVERLAP_LONG: '有些重复',
  MINOR_OVERLAP_LONG: '少量重复',
  NO_OVERLAP_LONG: '无明显重复',
  SOME_OVERLAP: '有些重复',
  MINOR_OVERLAP: '少量重复',
  SIGNIFICANT_OVERLAP: '显着重叠',
  NO_OVERLAP: '无明显重复',
  OVERLAP_TEXT: '你的顾客和这种状况间的糖链指数.',
  SYMPTOMS: '体征和症状',
  SYMPTOM_ONE: '通常无症状',
  SYMPTOM_TWO: '血压持续 >140/90 mmHg',
  SYMPTOM_THREE: '危重高血压表现 (头痛, 头晕, 呼吸困难等.)',
  SYMPTOM_FOUR: '冠心病表现 (如：间断性心痛, 呼吸困难)',
  SYMPTOM_FIVE: '外周动脉疾病表现 (例如，活动时腿痛)',
  SYMPTOM_SIX: '自限性胸痛 ± 放射到下巴或左肩/背',
  SYMPTOM_SEVEN: '呼吸困难',
  SYMPTOM_EIGHT: '其它(昏厥, 心悸, 腿肿, 端坐呼吸等.)',
  SYMPTOM_NINE: '腹部痉挛痛/左肩背',
  SYMPTOM_TEN: '反复性腹泻（或便血）',
  SYMPTOM_TEN_B: '里急后重',
  SYMPTOM_ELEVEN: '体重下降',
  SYMPTOM_TWELVE: '系统性症状 (如, 疲劳, 体重下降, 口腔溃疡, 脸颊潮红)',
  SYMPTOM_THIRTEEN: '组织特异性 (胸痛, 呼吸困难, 腿肿, 脸色苍白, etc.)',
  SYMPTOM_FOURTEEN: '关节疼痛和肿胀',
  SYMPTOM_FIFTEEN: '乏力',
  SYMPTOM_SIXTEEN: '口渴和多尿',
  SYMPTOM_SEVENTEEN: '伤口愈合减慢, 视力模糊, 口腔溃疡',
  SYMPTOM_EIGHTEEN: '呼吸困难',
  SYMPTOM_NINETEEN: '慢性咳嗽(± 咳痰)',
  SYMPTOM_TWENTY: '月经周期紊乱',
  SYMPTOM_TWENTYONE: '血管舒缩症状 (e.g., 潮热, 夜汗)',
  SYMPTOM_TWENTYTWO: '其它 (如，情绪不稳定，认知力下降，睡眠易醒)',
  SYMPTOM_TWENTYTHREE: '关节疼痛，肿胀，僵硬和红斑',
  SYMPTOM_TWENTYFOUR: '累及远端小关节 (手指、脚趾关节), 通常对称',
  SYMPTOM_TWENTYFIVE: '系统性症状 (乏力, 体重下降等.)',
  POSSIBLE_FOLLOW_UP: '可能伴随有',
  POSSIBLE_FOLLOW_UP_ONE: '连续血压测量± 24小时血压监控',
  POSSIBLE_FOLLOW_UP_TWO: '体重指数测量，体检',
  POSSIBLE_FOLLOW_UP_THREE: '血常规检查 (血脂, 肝肾功能)',
  POSSIBLE_FOLLOW_UP_FOUR: '血液检查: 血常规和血脂 (如, Lp(a), ApoB), 超敏C-反应蛋白, 同型半胱氨酸, 肝肾功能, 糖化血红蛋白',
  POSSIBLE_FOLLOW_UP_FIVE: '血压测量',
  POSSIBLE_FOLLOW_UP_SIX: '心电图',
  POSSIBLE_FOLLOW_UP_SEVEN: '其它心脏检查 (如, 心脏超声, 冠脉CT等)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: '其它心脏检查 (e.g., 冠状动脉钙化积分)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: '其它心脏检查 (e.g., 应激超声心动图)',
  POSSIBLE_FOLLOW_UP_EIGHT: '血液检查: 全血细胞计数, 肝肾功能, C-反应蛋白',
  POSSIBLE_FOLLOW_UP_NINE: '大便检查: 粪便免疫化学检测 (FIT), 粪便钙卫蛋白',
  POSSIBLE_FOLLOW_UP_TEN: 'CT和结肠镜检查',
  POSSIBLE_FOLLOW_UP_ELEVEN: '血液检查: 全血细胞计数, 肝肾功能, C-反应蛋白, 红细胞沉降率, 自身抗体 (如, 抗核抗体等)',
  POSSIBLE_FOLLOW_UP_TWELVE: '小便检查',
  POSSIBLE_FOLLOW_UP_THIRTEEN: '影像检查 (如, 胸腹部CT)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: '血液检查: 全血细胞计数, 肝肾功能,, 空腹血糖和胰岛素, 糖化血红蛋白 ',
  POSSIBLE_FOLLOW_UP_FIFTEEN: '血脂检查: 血常规和其它(包括：oxLDL, VLDL, LDL-P, Lp-PLA2, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: '其它血压检查, 超敏C-反应蛋白, 同型半胱氨酸, 肝肾功能, 糖化血红蛋白',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: '血液检查: 全血细胞计数',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: '肺活量检查',
  POSSIBLE_FOLLOW_UP_NINETEEN: '心电图，胸透',
  POSSIBLE_FOLLOW_UP_TWENTY: '血液检查 (包括. 卵泡刺激素 雌二醇, 黄体酮, 睾酮, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: '看临绝经期医学专家',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: '血液检查: 全血细胞计数, 类风湿因子, 环瓜氨酸肽抗体, C-反应蛋白',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: '关节影像检查，CT或核磁共振',
  PERCENTILE: '百分位',
  SINGLE_PERCENTILE: '百分位',
  RISK_FACTORS: '风险因子',
  RISK_FACTOR_ONE: '既往史 (心脏代谢综合征, 自身免疫性疾病)',
  RISK_FACTOR_TWO: '就医史 (如，抑制素, 接受大量输液 )',
  RISK_FACTOR_THREE: '吸烟情况（包括现在和过去）',
  RANKS_YOU: '这个结果把您排序在',
  THIS_RESULT_RANKS_IN_THE: '这个结果排序在',
  RELATED_RESEARCH_PAPERS: '相关研究文献',
  YOUR_RESULT: '您的结果',
  CHRONIC_INFLAMMATION: '慢性炎症',
  SYSTEMIC_INFLAMMATION: '系统性炎症',
  ANTI_INFLAMMATORY: '抗炎的',
  ANTI_INFLAMMATORY_INDEX: '抗炎指数',
  PRO_INFLAMMATORY: '促炎的',
  PRO_INFLAMMATORY_INDEX: '促炎指数',
  SUPPORTIVE_INDEX: '支持指数',
  GLYCAN_SHIELD: '少年糖链 (S)',
  GLYCAN_YOUTH: '青年糖链 (G2)',
  GLYCAN_MATURE: '老化糖链 (G0)',
  GLYCAN_MEDIAN: '中性糖链 (G1)',
  GLYCAN_LIFESTYLE: '受损糖链 (B)',
  GLYCAN_LIFESTYLE_B: '平分型糖链 (B)',
  WORSE: '更差',
  BETTER: '更好',
  OPTIMAL: '最佳',
  SUBOPTIMAL: '次优',
  AVERAGE: '平均',
  INDEX_SCORE: '指数分值',
  MEASURED_RESULT: '检查结果',
  POPULATION_AVERAGE: '人群平均',
  AGE: '年龄',
  SAME_AS: '同样',
  THAN: '更',
  YEAR_OLDER: '更老',
  YEARS_OLDER: '更老',
  YEAR_YOUNGER: '更年轻',
  YEARS_YOUNGER: '更年轻',
  AREA: '系统',
  CONDITION: '细分',
  OVERLAPS: '相关性',
  INDEX_OVERLAPS: '相关性',
  CARDIOVASCULAR: '心血管',
  CARDIOVASCULAR_HEALTH: '心血管',
  METABOLIC: '代谢',
  METABOLIC_HEALTH: '代谢',
  AUTOIMMUNE: '自身免疫',
  AUTOIMMUNE_HEALTH: '自身免疫',
  RESPIRATORY: '呼吸系统',
  RESPIRATORY_HEALTH: '呼吸系统',
  FEMALE: '仅女性',
  FEMALE_HEALTH: '仅女性',
  RISK_OF_HYPER: '高血压风险',
  PRE_HYPERTENSION: '高血压前期',
  HYPERTENSION: '高血压',
  MI_CVA: '心梗和卒中',
  ATHEROSCLEROSIS: '动脉粥样硬化',
  CORONARY: '冠心病',
  TYPE_2_DIABETES: 'II型糖尿病',
  DYSLIPIDEMIA: '高血脂',
  RHEUMATOID: '类风湿性关节炎',
  ULCERATIVE_COLITIS: '溃疡性结肠炎（UC)',
  CROHN: '克罗恩病',
  SLE: '系统性红斑狼疮（SLE)',
  COPD: '慢阻肺（慢性阻塞性肺病）COPD',
  PERIMENOPAUSE: '临绝经期/更年前期',
  NO_SIGNIFICANT_OVERLAP: '无相关性',
  RANKS_YOU_BEFORE: '您的结果优于',
  RANKS_YOU_AFTER: '的人',
  NO_SIGNIFICANT_AREAS: '没有需要注意的重要领域',
  SOME_AREAS: '一些需要注意的地方',
  SIGNIFICANT_AREAS: '值得关注的重要领域',
  SLIGHTLY_OUT_OF_RANGE: '稍微超出范围',
  SIGNIFICANTLY_OUT_OF_RANGE: '明显超出范围',
  AREAS_FOR_ATTENTION: '需要注意的地方',
  PLEASE_NOTE: '请注意',
  PLEASE_NOTE_SENTENCE: '虽然某些模式可能与在特定条件下观察到的模式相似，但这并不能证实疾病或任何亚临床形式的存在'
};

