export let english = {
  BIOLOGICAL_AGE: 'Biological age',
  CHRONOLOGICAL_AGE: 'Chronological age',
  CHRONOLOGICAL_AGE_TWO: 'chronological age',
  SI_SCORE: 'SI score',
  GLYCAN: 'Glycan',
  PEAK: 'Peak',
  LOWER_THAN_AVERAGE: 'Lower than average',
  BELOW_AVERAGE: 'Below average',
  AROUND_AVERAGE: 'Around average',
  HIGHER_THAN_AVERAGE: 'Higher than average',
  ABOVE_AVERAGE: 'Above average',
  SOME_OVERLAP_LONG: 'Some overlap',
  MINOR_OVERLAP_LONG: 'Minor overlap',
  NO_OVERLAP_LONG: 'No significant overlap',
  SOME_OVERLAP: 'Some overlap',
  MINOR_OVERLAP: 'Minor overlap',
  NO_OVERLAP: 'No significant overlap',
  OVERLAP_TEXT: 'of glycan indexes between your patient and this condition.',
  SYMPTOMS: 'Signs and symptoms',
  SYMPTOM_ONE: 'Usually asymptomatic',
  SYMPTOM_TWO: 'BP consistently >140/90 mmHg',
  SYMPTOM_THREE: 'Signs of malignant hypertension (headache, dizziness, breathlessness, etc.)',
  SYMPTOM_FOUR: 'Signs of coronary artery disease (e.g., self-resolving chest pain, breathlessness)',
  SYMPTOM_FIVE: 'Signs of peripheral artery disease (e.g., leg pain during activity)',
  SYMPTOM_SIX: 'Self-limiting chest pain ± radiation into jaw/left arm/back',
  SYMPTOM_SEVEN: 'Breathlessness',
  SYMPTOM_EIGHT: 'Other (syncope, palpitations, leg edema, orthopnea, etc.)',
  SYMPTOM_NINE: 'Abdominal pain and cramping/left arm/back',
  SYMPTOM_TEN: 'Recurring diarrhea (± blood)',
  SYMPTOM_TEN_B: 'Urgency to defecate',
  SYMPTOM_ELEVEN: 'Weight loss',
  SYMPTOM_TWELVE: 'Systemic (e.g., fatigue, weight loss, mouth ulcers, butterfly skin rash)',
  SYMPTOM_THIRTEEN: 'Organ-specific (chest pain, difficulty breathing, leg swelling, anaemia, etc.)',
  SYMPTOM_FOURTEEN: 'Joint pain and swelling',
  SYMPTOM_FIFTEEN: 'Fatigue',
  SYMPTOM_SIXTEEN: 'Increased thirst and frequent urination',
  SYMPTOM_SEVENTEEN: 'Slow wound healing, blurred vision, frequent thrush',
  SYMPTOM_EIGHTEEN: 'Difficulty breathing',
  SYMPTOM_NINETEEN: 'Chronic cough (± productive)',
  SYMPTOM_TWENTY: 'Irregular menstrual cycle',
  SYMPTOM_TWENTYONE: 'Vasomotor symptoms (e.g., hot flushes, night sweats)',
  SYMPTOM_TWENTYTWO: 'Other (e.g., mood swings, cognitive difficulties, sleep disturbance)',
  SYMPTOM_TWENTYTHREE: 'Joint pain, swelling, stiffness and erythema',
  SYMPTOM_TWENTYFOUR: 'Smaller and distant joint involvement (fingers, toes), usually symmetrical',
  SYMPTOM_TWENTYFIVE: 'Systemic (fatigue, weight loss, etc.)',
  POSSIBLE_FOLLOW_UP: 'Possible follow-up',
  POSSIBLE_FOLLOW_UP_ONE: 'Serial blood pressure (BP) measurements Â± 24-hour BP monitoring',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI and/or body composition check',
  POSSIBLE_FOLLOW_UP_THREE: 'Basic bloods (lipid profile, renal and liver function)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Blood tests: basic and extended lipid profile (e.g., Lp(a), ApoB), hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'BP check',
  POSSIBLE_FOLLOW_UP_SIX: 'ECG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Cardiology referral for other tests (e.g., cardiac echo, coronary CT)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Cardiology referral for other tests (e.g., coronary artery calcium score)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Cardiology referral for other tests (e.g., stress echocardiogram)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Blood tests: full blood count, renal and liver function, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Stool tests: faecal immunochemical test (FIT), faecal calprotectin',
  POSSIBLE_FOLLOW_UP_TEN: 'Referral for CT colonoscopy',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Blood tests: full blood count, renal and liver function, CRP, ESR, autoantibodies (e.g., ANA, anti-dsDNA)',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Urinalysis',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Organ-targeted imaging (e.g., CT thorax, CT abdomen)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Blood tests: full blood count, renal and liver function, fasting glucose and insulin, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Lipid profile blood tests: basic and extended (incl. oxLDL, VLDL, LDL-P, Lp-PLA2, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Other blood tests hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Blood tests: full blood count',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometry',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'ECG, chest X-ray',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Blood tests (incl. FSH, oestradiol, progesterone, testosterone, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Referral to (peri)menopause specialist/gynaecologist',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Blood tests: full blood count, rheumatoid factor, anti-CCP antibodies, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Joint imaging (X-rays, MRI)',
  PERCENTILE: 'percentile',
  SINGLE_PERCENTILE: 'percentile',
  RISK_FACTORS: 'Risk factors',
  RISK_FACTOR_ONE: 'Past medical history (cardiometabolic syndrome, autoimmune disease)',
  RISK_FACTOR_TWO: 'Medication history (e.g., statins, blood thinners)',
  RISK_FACTOR_THREE: 'Current/previous smoking history',
  RANKS_YOU: 'This result ranks you in the',
  THIS_RESULT_RANKS_IN_THE: 'This result ranks in the',
  RELATED_RESEARCH_PAPERS: 'Related research papers',
  YOUR_RESULT: 'Your result',
  CHRONIC_INFLAMMATION: 'Chronic inflammation',
  SYSTEMIC_INFLAMMATION: 'Systemic inflammation',
  ANTI_INFLAMMATORY: 'Anti-inflammatory',
  ANTI_INFLAMMATORY_INDEX: 'Anti-inflammatory index',
  PRO_INFLAMMATORY: 'Pro-inflammatory',
  PRO_INFLAMMATORY_INDEX: 'Pro-inflammatory index',
  SUPPORTIVE_INDEX: 'Supportive index',
  GLYCAN_SHIELD: 'Glycan Shield (S)',
  GLYCAN_YOUTH: 'Glycan Youth (G2)',
  GLYCAN_MATURE: 'Glycan Mature (G0)',
  GLYCAN_MEDIAN: 'Glycan Median (G1)',
  GLYCAN_LIFESTYLE: 'Glycan Lifestyle (B)',
  GLYCAN_LIFESTYLE_B: 'Glycan Bisection (B)',
  WORSE: 'Worse',
  BETTER: 'Better',
  OPTIMAL: 'Optimal',
  SUBOPTIMAL: 'Suboptimal',
  AVERAGE: 'Average',
  INDEX_SCORE: 'Index score',
  MEASURED_RESULT: 'Measured result',
  POPULATION_AVERAGE: 'Population average',
  AGE: 'Age',
  SAME_AS: 'Same as',
  THAN: 'than',
  YEAR_OLDER: 'year older',
  YEARS_OLDER: 'years older',
  YEAR_YOUNGER: 'year younger',
  YEARS_YOUNGER: 'years younger',
  AREA: 'Area',
  CONDITION: 'Condition',
  OVERLAPS: 'Overlaps',
  INDEX_OVERLAPS: 'Index overlaps',
  CARDIOVASCULAR: 'Cardiovascular',
  CARDIOVASCULAR_HEALTH: 'Cardiovascular health',
  METABOLIC: 'Metabolic',
  METABOLIC_HEALTH: 'Metabolic health',
  AUTOIMMUNE: 'Autoimmune',
  AUTOIMMUNE_HEALTH: 'Autoimmune health',
  RESPIRATORY: 'Respiratory',
  RESPIRATORY_HEALTH: 'Respiratory health',
  FEMALE: 'Female',
  FEMALE_HEALTH: 'Female health',
  RISK_OF_HYPER: 'Inc. risk of hypertension',
  PRE_HYPERTENSION: 'Pre-hypertension',
  HYPERTENSION: 'Hypertension',
  MI_CVA: 'MI & CVA',
  ATHEROSCLEROSIS: 'Atherosclerosis',
  CORONARY: 'Coronary artery disease',
  TYPE_2_DIABETES: 'Type 2 diabetes',
  DYSLIPIDEMIA: 'Dyslipidemia',
  RHEUMATOID: 'Rheumatoid arthritis',
  ULCERATIVE_COLITIS: 'Ulcerative colitis',
  CROHN: "Crohn's disease",
  SLE: 'SLE',
  COPD: 'COPD',
  PERIMENOPAUSE: 'Perimenopause',
  NO_SIGNIFICANT_OVERLAP: 'No significant overlap',
  SIGNIFICANT_OVERLAP: 'Significant overlap',
  NO_SIGNIFICANT_AREAS: 'No significant areas for attention',
  SOME_AREAS: 'Some areas for attention',
  SIGNIFICANT_AREAS: 'Significant areas for attention',
  SLIGHTLY_OUT_OF_RANGE: 'Slightly out of range',
  SIGNIFICANTLY_OUT_OF_RANGE: 'Significantly out of range',
  AREAS_FOR_ATTENTION: 'Areas for attention',
  PLEASE_NOTE: 'Please note',
  PLEASE_NOTE_SENTENCE: 'While certain patterns may show similarities to those observed in specific conditions, this does not confirm the presence of a disease or any of its subclinical forms.',
};

export let polish = {
  BIOLOGICAL_AGE: 'Wiek biologiczny',
  CHRONOLOGICAL_AGE: 'Wiek Kalendarzowy',
  GLYCAN: 'Glikan',
  PEAK: 'Pik',
  LOWER_THAN_AVERAGE: 'niższy od wartości średniej',
  AROUND_AVERAGE: 'W okolicach wartości średniej',
  HIGHER_THAN_AVERAGE: 'wyższy od wartości średniej',
  SOME_OVERLAP_LONG: 'Znaczny stopień pokrywania się',
  MINOR_OVERLAP_LONG: 'Nieznaczne stopień pokrywania się',
  NO_OVERLAP_LONG: 'Brak znaczącego pokrywania się',
  SOME_OVERLAP: 'Częściowy',
  MINOR_OVERLAP: 'Niewielki',
  NO_OVERLAP: 'Brak',
  OVERLAP_TEXT: 'indeksów glikanowych między pacjentem a badanymi z tym schorzeniem.',
  SYMPTOMS: 'Sygnały i objawy',
  SYMPTOM_ONE: 'Przeważnie przebiega w sposób bezobjawowy',
  SYMPTOM_TWO: 'Ciśnienie tętnicze stale >140/90 mmHg',
  SYMPTOM_THREE: 'Objawy nadciśnienia złośliwego (ból głowy, zawroty głowy, duszność itp.)',
  SYMPTOM_FOUR: 'Objawy choroby wieńcowej (np. samoistnie ustępujący ból w klatce piersiowej, bezdech)',
  SYMPTOM_FIVE: 'Objawy choroby tętnic obwodowych (np. ból nóg podczas aktywności)',
  SYMPTOM_SIX: 'Samoograniczający się ból w klatce piersiowej ± promieniujący do szczęki/lewego ramienia/pleców',
  SYMPTOM_SEVEN: 'Duszność',
  SYMPTOM_EIGHT: 'Inne (omdlenia, kołatanie serca, obrzęk nóg, orhhopnoe itp.)',
  SYMPTOM_NINE: 'Ból brzucha i skurcze',
  SYMPTOM_TEN: 'Nawracająca biegunka (± krew)',
  SYMPTOM_TEN_B: 'Nagła potrzeba wypróżnienia',
  SYMPTOM_ELEVEN: 'Utrata masy ciała',
  SYMPTOM_TWELVE: 'Ogólnoustrojowe (np. zmęczenie, utrata masy ciała, owrzodzenia jamy ustnej, wysypka w kształcie motyla w okolicy policzków i nosa)',
  SYMPTOM_THIRTEEN: 'Narządowe (ból w klatce piersiowej, trudności w oddychaniu, obrzęk nóg, niedokrwistość itp.)',
  SYMPTOM_FOURTEEN: 'Ból i obrzęk stawów',
  SYMPTOM_FIFTEEN: 'Zmęczenie',
  SYMPTOM_SIXTEEN: 'Zwiększone pragnienie i częste oddawanie moczu',
  SYMPTOM_SEVENTEEN: 'Powolne gojenie się ran, niewyraźne widzenie, częste pleśniawki',
  SYMPTOM_EIGHTEEN: 'Trudności w oddychaniu',
  SYMPTOM_NINETEEN: 'Przewlekły kaszel (± produktywny)',
  SYMPTOM_TWENTY: 'Nieregularny cykl menstruacyjny',
  SYMPTOM_TWENTYONE: 'Objawy naczynioruchowe (np. uderzenia gorąca)',
  SYMPTOM_TWENTYTWO: 'Inne (np. wahania nastroju, trudności poznawcze, zaburzenia snu)',
  SYMPTOM_TWENTYTHREE: 'Ból stawów, obrzęk, sztywność i rumień',
  SYMPTOM_TWENTYFOUR: 'Zajęcie mniejszych stawów dystalnych (palce rąk i nóg), zwykle symetryczne',
  SYMPTOM_TWENTYFIVE: 'Ogólnoustrojowe (zmęczenie, utrata masy ciała itp.)',
  POSSIBLE_FOLLOW_UP: 'Ewentualne dalsze działania',
  POSSIBLE_FOLLOW_UP_ONE: 'Seryjne pomiary ciśnienia tętniczego i/lub 24-godzinne monitorowanie ciśnienia tętniczego',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI i/lub kontrola składu ciała',
  POSSIBLE_FOLLOW_UP_THREE: 'Podstawowe badania krwi (profil lipidowy, czynność nerek i wątroby)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Badania krwi: podstawowy i rozszerzony profil lipidowy (np. Lp(a), ApoB), hsCRP, homocysteina, czynność nerek i wątroby, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'Kontrola ciśnienia tętniczego',
  POSSIBLE_FOLLOW_UP_SIX: 'EKG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Skierowanie do kardiologa na inne badania (np. echo serca, TK naczyń wieńcowych)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Skierowanie do kardiologa na inne badania (np. wskaźnik uwapnienia tętnic wieńcowych)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Skierowanie do kardiologa na inne badania (np. echokardiogram wysiłkowy)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Badania kału: test na obecność krwi utajonej (FIT), kalprotektyna w kale',
  POSSIBLE_FOLLOW_UP_TEN: 'Skierowanie na kolonoskopię, TK',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, CRP, OB, autoprzeciwciała (np. ANA, w tym anty-dsDNA).',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Badanie ogólne moczu',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Badania obrazowe ukierunkowane na narządy (np. TK klatki piersiowej, TK jamy brzusznej)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, stężenie glukozy i insuliny na czczo, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Badania profilu lipidowego krwi: podstawowe i rozszerzone (np. oxLDL, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Inne badania krwi hsCRP, homocysteina, czynność nerek i wątroby, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Badania krwi: pełna morfologia krwi',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometria',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'EKG, RTG klatki piersiowej',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Badania krwi (w tym FSH, estradiol, progesteron, testosteron, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Skierowanie do specjalisty/ginekologa zajmującego się (peri)menopauzą',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Badania krwi: pełna morfologia krwi, czynnik reumatoidalny, przeciwciała anty-CCP, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Obrazowanie stawów (zdjęcia rentgenowskie, rezonans magnetyczny)',
  PERCENTILE: 'percentylu',
  SINGLE_PERCENTILE: 'percentyl',
  RISK_FACTORS: 'Czynniki ryzyka',
  RISK_FACTOR_ONE: 'Historia chorób (np. zespół kardiometaboliczny, choroby autoimmunologiczne)',
  RISK_FACTOR_TWO: 'Historia przyjmowania leków (np. statyn, leków przeciwzakrzepowych)',
  RISK_FACTOR_THREE: 'Palenie tytoniu',
  RANKS_YOU: 'Twoj wynik klasyfikuje Cię w',
  RELATED_RESEARCH_PAPERS: 'Publikacje naukowe',
  YOUR_RESULT: 'Twój wynik',
  CHRONIC_INFLAMMATION: 'TempText POLISH1',
  ANTI_INFLAMMATORY: 'TempText POLISH2',
  PRO_INFLAMMATORY: 'TempText POLISH3',
  SUPPORTIVE_INDEX: 'TempText POLISH4',
  GLYCAN_SHIELD: 'TempText Shield (S)',
  GLYCAN_YOUTH: 'TempText Youth (G2)',
  GLYCAN_MATURE: 'TempText Mature (G0)',
  GLYCAN_MEDIAN: 'TempText Median (G1)',
  GLYCAN_LIFESTYLE: 'TempText Lifestyle (B)',
  WORSE: 'TempText Worse',
  BETTER: 'TempText Better',
  AVERAGE: 'TempText Average',
};

export let slovenian = {
  BIOLOGICAL_AGE: 'Biološka starost',
  CHRONOLOGICAL_AGE: 'Kronološka starost',
  CHRONOLOGICAL_AGE_TWO: 'kronološke starosti',
  RANKS_YOU: 'Ta rezultat vas uvršča med',
  PERCENTILE: 'percentilov',
  SINGLE_PERCENTILE: 'percentil',
  YOUR_RESULT: 'Vaš rezultat',
  GLYCAN_SHIELD: 'Glikanski ščit (S)',
  GLYCAN_YOUTH: 'Mladost glikanov (G2)',
  GLYCAN_MATURE: 'Zrelost glikanov (G0)',
  GLYCAN_MEDIAN: 'Povprečje glikanov (G1)',
  GLYCAN_LIFESTYLE: 'Življenjski slog glikanov (B)',
  GLYCAN_LIFESTYLE_B: 'Življenjski slog glikanov (B)',
  CHRONIC_INFLAMMATION: 'Kronično vnetje',
  ANTI_INFLAMMATORY: 'Protivnetni',
  ANTI_INFLAMMATORY_INDEX: 'Protivnetni index',
  PRO_INFLAMMATORY: 'Pro-vnetni',
  PRO_INFLAMMATORY_INDEX: 'Pro-vnetni index',
  SUPPORTIVE_INDEX: 'Podporni kazalnik',
  WORSE: 'Slabše',
  BETTER: 'Boljše',
  OPTIMAL: 'Optimalen',
  SUBOPTIMAL: 'neoptimalno',
  AVERAGE: 'Povprečje',
  AROUND_AVERAGE: 'Približno povprečje',
  THIS_RESULT_RANKS_IN_THE: 'Ta rezultat se uvršča med',
  INDEX_SCORE: 'Rezultat kazalnika',
  MEASURED_RESULT: 'Vaš rezultat',
  POPULATION_AVERAGE: 'Povprečje prebivalstva',
  AGE: 'Dob',
  SAME_AS: 'Enako kot',
  THAN: 'od',
  YEAR_OLDER: 'starejši',
  YEARS_OLDER: 'starejši',
  YEAR_YOUNGER: 'let mlajši',
  YEARS_YOUNGER: 'let mlajši'
};

export let japanese = {
  BIOLOGICAL_AGE: '生物学的年齢',
  CHRONOLOGICAL_AGE: '暦年齢',
  CHRONOLOGICAL_AGE_TWO: '暦年齢',
  SI_SCORE: 'SI score',
  GLYCAN: 'Glycan',
  PEAK: 'Peak',
  LOWER_THAN_AVERAGE: 'Lower than average',
  BELOW_AVERAGE: 'Below average',
  AROUND_AVERAGE: '平均値くらい',
  HIGHER_THAN_AVERAGE: 'Higher than average',
  ABOVE_AVERAGE: 'Above average',
  SOME_OVERLAP_LONG: 'Some overlap',
  MINOR_OVERLAP_LONG: 'Minor overlap',
  NO_OVERLAP_LONG: 'No significant overlap',
  SOME_OVERLAP: 'Some overlap',
  MINOR_OVERLAP: 'Minor overlap',
  NO_OVERLAP: 'No significant overlap',
  OVERLAP_TEXT: 'of glycan indexes between your patient and this condition.',
  SYMPTOMS: 'Signs and symptoms',
  SYMPTOM_ONE: 'Usually asymptomatic',
  SYMPTOM_TWO: 'BP consistently >140/90 mmHg',
  SYMPTOM_THREE: 'Signs of malignant hypertension (headache, dizziness, breathlessness, etc.)',
  SYMPTOM_FOUR: 'Signs of coronary artery disease (e.g., self-resolving chest pain, breathlessness)',
  SYMPTOM_FIVE: 'Signs of peripheral artery disease (e.g., leg pain during activity)',
  SYMPTOM_SIX: 'Self-limiting chest pain ± radiation into jaw/left arm/back',
  SYMPTOM_SEVEN: 'Breathlessness',
  SYMPTOM_EIGHT: 'Other (syncope, palpitations, leg edema, orthopnea, etc.)',
  SYMPTOM_NINE: 'Abdominal pain and cramping/left arm/back',
  SYMPTOM_TEN: 'Recurring diarrhea (± blood)',
  SYMPTOM_TEN_B: 'Urgency to defecate',
  SYMPTOM_ELEVEN: 'Weight loss',
  SYMPTOM_TWELVE: 'Systemic (e.g., fatigue, weight loss, mouth ulcers, butterfly skin rash)',
  SYMPTOM_THIRTEEN: 'Organ-specific (chest pain, difficulty breathing, leg swelling, anaemia, etc.)',
  SYMPTOM_FOURTEEN: 'Joint pain and swelling',
  SYMPTOM_FIFTEEN: 'Fatigue',
  SYMPTOM_SIXTEEN: 'Increased thirst and frequent urination',
  SYMPTOM_SEVENTEEN: 'Slow wound healing, blurred vision, frequent thrush',
  SYMPTOM_EIGHTEEN: 'Difficulty breathing',
  SYMPTOM_NINETEEN: 'Chronic cough (± productive)',
  SYMPTOM_TWENTY: 'Irregular menstrual cycle',
  SYMPTOM_TWENTYONE: 'Vasomotor symptoms (e.g., hot flushes, night sweats)',
  SYMPTOM_TWENTYTWO: 'Other (e.g., mood swings, cognitive difficulties, sleep disturbance)',
  SYMPTOM_TWENTYTHREE: 'Joint pain, swelling, stiffness and erythema',
  SYMPTOM_TWENTYFOUR: 'Smaller and distant joint involvement (fingers, toes), usually symmetrical',
  SYMPTOM_TWENTYFIVE: 'Systemic (fatigue, weight loss, etc.)',
  POSSIBLE_FOLLOW_UP: 'Possible follow-up',
  POSSIBLE_FOLLOW_UP_ONE: 'Serial blood pressure (BP) measurements Â± 24-hour BP monitoring',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI and/or body composition check',
  POSSIBLE_FOLLOW_UP_THREE: 'Basic bloods (lipid profile, renal and liver function)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Blood tests: basic and extended lipid profile (e.g., Lp(a), ApoB), hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'BP check',
  POSSIBLE_FOLLOW_UP_SIX: 'ECG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Cardiology referral for other tests (e.g., cardiac echo, coronary CT)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Cardiology referral for other tests (e.g., coronary artery calcium score)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Cardiology referral for other tests (e.g., stress echocardiogram)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Blood tests: full blood count, renal and liver function, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Stool tests: faecal immunochemical test (FIT), faecal calprotectin',
  POSSIBLE_FOLLOW_UP_TEN: 'Referral for CT colonoscopy',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Blood tests: full blood count, renal and liver function, CRP, ESR, autoantibodies (e.g., ANA, anti-dsDNA)',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Urinalysis',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Organ-targeted imaging (e.g., CT thorax, CT abdomen)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Blood tests: full blood count, renal and liver function, fasting glucose and insulin, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Lipid profile blood tests: basic and extended (incl. oxLDL, VLDL, LDL-P, Lp-PLA2, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Other blood tests hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Blood tests: full blood count',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometry',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'ECG, chest X-ray',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Blood tests (incl. FSH, oestradiol, progesterone, testosterone, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Referral to (peri)menopause specialist/gynaecologist',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Blood tests: full blood count, rheumatoid factor, anti-CCP antibodies, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Joint imaging (X-rays, MRI)',
  PERCENTILE: 'パーセンタイル',
  SINGLE_PERCENTILE: 'パーセンタイル',
  RISK_FACTORS: 'Risk factors',
  RISK_FACTOR_ONE: 'Past medical history (cardiometabolic syndrome, autoimmune disease)',
  RISK_FACTOR_TWO: 'Medication history (e.g., statins, blood thinners)',
  RISK_FACTOR_THREE: 'Current/previous smoking history',
  RANKS_YOU: 'この結果により、あなたは',
  THIS_RESULT_RANKS_IN_THE: 'この結果は、',
  RELATED_RESEARCH_PAPERS: 'Related research papers',
  YOUR_RESULT: 'Your result',
  CHRONIC_INFLAMMATION: '慢性炎症',
  SYSTEMIC_INFLAMMATION: '全身性炎症',
  ANTI_INFLAMMATORY: '抗炎症性',
  ANTI_INFLAMMATORY_INDEX: '抗炎症性',
  PRO_INFLAMMATORY: '炎症誘発性',
  PRO_INFLAMMATORY_INDEX: '炎症誘発性',
  SUPPORTIVE_INDEX: 'サポート指標',
  GLYCAN_SHIELD: 'Glycan Shield (S)',
  GLYCAN_YOUTH: 'Glycan Youth (G2)',
  GLYCAN_MATURE: 'Glycan Mature (G0)',
  GLYCAN_MEDIAN: 'Glycan Median (G1)',
  GLYCAN_LIFESTYLE: 'Glycan Lifestyle (B)',
  GLYCAN_LIFESTYLE_B: 'Glycan Bisection (B)',
  WORSE: 'より年上',
  BETTER: 'より若い',
  OPTIMAL: '最適な',
  SUBOPTIMAL: '最適ではない',
  AVERAGE: '平均値',
  INDEX_SCORE: '指標スコア',
  MEASURED_RESULT: 'あなたの結果',
  POPULATION_AVERAGE: '母集団平均',
  AGE: '年齢',
  SAME_AS: '〜と同じ',
  THAN: 'より',
  YEAR_OLDER: '年上',
  YEARS_OLDER: '年上',
  YEAR_YOUNGER: '年下',
  YEARS_YOUNGER: '年下',
};

export let chinese = {
  BIOLOGICAL_AGE: '生物学年龄',
  CHRONOLOGICAL_AGE: '实际年龄',
  CHRONOLOGICAL_AGE_TWO: '实际年龄',
  SI_SCORE: 'SI 分值',
  GLYCAN: '糖链',
  PEAK: '峰',
  LOWER_THAN_AVERAGE: '低于平均数',
  BELOW_AVERAGE: '平均以下',
  AROUND_AVERAGE: '接近平均',
  HIGHER_THAN_AVERAGE: '高于平均数',
  ABOVE_AVERAGE: '平均以上',
  SOME_OVERLAP_LONG: '有些重复',
  MINOR_OVERLAP_LONG: '少量重复',
  NO_OVERLAP_LONG: '无明显重复',
  SOME_OVERLAP: '有些重复',
  MINOR_OVERLAP: '少量重复',
  SIGNIFICANT_OVERLAP: '显着重叠',
  NO_OVERLAP: '无明显重复',
  OVERLAP_TEXT: '你的顾客和这种状况间的糖链指数.',
  SYMPTOMS: '体征和症状',
  SYMPTOM_ONE: '通常无症状',
  SYMPTOM_TWO: '血压持续 >140/90 mmHg',
  SYMPTOM_THREE: '危重高血压表现 (头痛, 头晕, 呼吸困难等.)',
  SYMPTOM_FOUR: '冠心病表现 (如：间断性心痛, 呼吸困难)',
  SYMPTOM_FIVE: '外周动脉疾病表现 (例如，活动时腿痛)',
  SYMPTOM_SIX: '自限性胸痛 ± 放射到下巴或左肩/背',
  SYMPTOM_SEVEN: '呼吸困难',
  SYMPTOM_EIGHT: '其它(昏厥, 心悸, 腿肿, 端坐呼吸等.)',
  SYMPTOM_NINE: '腹部痉挛痛/左肩背',
  SYMPTOM_TEN: '反复性腹泻（或便血）',
  SYMPTOM_TEN_B: '里急后重',
  SYMPTOM_ELEVEN: '体重下降',
  SYMPTOM_TWELVE: '系统性症状 (如, 疲劳, 体重下降, 口腔溃疡, 脸颊潮红)',
  SYMPTOM_THIRTEEN: '组织特异性 (胸痛, 呼吸困难, 腿肿, 脸色苍白, etc.)',
  SYMPTOM_FOURTEEN: '关节疼痛和肿胀',
  SYMPTOM_FIFTEEN: '乏力',
  SYMPTOM_SIXTEEN: '口渴和多尿',
  SYMPTOM_SEVENTEEN: '伤口愈合减慢, 视力模糊, 口腔溃疡',
  SYMPTOM_EIGHTEEN: '呼吸困难',
  SYMPTOM_NINETEEN: '慢性咳嗽(± 咳痰)',
  SYMPTOM_TWENTY: '月经周期紊乱',
  SYMPTOM_TWENTYONE: '血管舒缩症状 (e.g., 潮热, 夜汗)',
  SYMPTOM_TWENTYTWO: '其它 (如，情绪不稳定，认知力下降，睡眠易醒)',
  SYMPTOM_TWENTYTHREE: '关节疼痛，肿胀，僵硬和红斑',
  SYMPTOM_TWENTYFOUR: '累及远端小关节 (手指、脚趾关节), 通常对称',
  SYMPTOM_TWENTYFIVE: '系统性症状 (乏力, 体重下降等.)',
  POSSIBLE_FOLLOW_UP: '可能伴随有',
  POSSIBLE_FOLLOW_UP_ONE: '连续血压测量± 24小时血压监控',
  POSSIBLE_FOLLOW_UP_TWO: '体重指数测量，体检',
  POSSIBLE_FOLLOW_UP_THREE: '血常规检查 (血脂, 肝肾功能)',
  POSSIBLE_FOLLOW_UP_FOUR: '血液检查: 血常规和血脂 (如, Lp(a), ApoB), 超敏C-反应蛋白, 同型半胱氨酸, 肝肾功能, 糖化血红蛋白',
  POSSIBLE_FOLLOW_UP_FIVE: '血压测量',
  POSSIBLE_FOLLOW_UP_SIX: '心电图',
  POSSIBLE_FOLLOW_UP_SEVEN: '其它心脏检查 (如, 心脏超声, 冠脉CT等)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: '其它心脏检查 (e.g., 冠状动脉钙化积分)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: '其它心脏检查 (e.g., 应激超声心动图)',
  POSSIBLE_FOLLOW_UP_EIGHT: '血液检查: 全血细胞计数, 肝肾功能, C-反应蛋白',
  POSSIBLE_FOLLOW_UP_NINE: '大便检查: 粪便免疫化学检测 (FIT), 粪便钙卫蛋白',
  POSSIBLE_FOLLOW_UP_TEN: 'CT和结肠镜检查',
  POSSIBLE_FOLLOW_UP_ELEVEN: '血液检查: 全血细胞计数, 肝肾功能, C-反应蛋白, 红细胞沉降率, 自身抗体 (如, 抗核抗体等)',
  POSSIBLE_FOLLOW_UP_TWELVE: '小便检查',
  POSSIBLE_FOLLOW_UP_THIRTEEN: '影像检查 (如, 胸腹部CT)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: '血液检查: 全血细胞计数, 肝肾功能,, 空腹血糖和胰岛素, 糖化血红蛋白 ',
  POSSIBLE_FOLLOW_UP_FIFTEEN: '血脂检查: 血常规和其它(包括：oxLDL, VLDL, LDL-P, Lp-PLA2, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: '其它血压检查, 超敏C-反应蛋白, 同型半胱氨酸, 肝肾功能, 糖化血红蛋白',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: '血液检查: 全血细胞计数',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: '肺活量检查',
  POSSIBLE_FOLLOW_UP_NINETEEN: '心电图，胸透',
  POSSIBLE_FOLLOW_UP_TWENTY: '血液检查 (包括. 卵泡刺激素 雌二醇, 黄体酮, 睾酮, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: '看临绝经期医学专家',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: '血液检查: 全血细胞计数, 类风湿因子, 环瓜氨酸肽抗体, C-反应蛋白',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: '关节影像检查，CT或核磁共振',
  PERCENTILE: '百分位',
  SINGLE_PERCENTILE: '百分位',
  RISK_FACTORS: '风险因子',
  RISK_FACTOR_ONE: '既往史 (心脏代谢综合征, 自身免疫性疾病)',
  RISK_FACTOR_TWO: '就医史 (如，抑制素, 接受大量输液 )',
  RISK_FACTOR_THREE: '吸烟情况（包括现在和过去）',
  RANKS_YOU: '这个结果把您排序在',
  THIS_RESULT_RANKS_IN_THE: '这个结果排序在',
  RELATED_RESEARCH_PAPERS: '相关研究文献',
  YOUR_RESULT: '您的结果',
  CHRONIC_INFLAMMATION: '慢性炎症',
  SYSTEMIC_INFLAMMATION: '系统性炎症',
  ANTI_INFLAMMATORY: '抗炎的',
  ANTI_INFLAMMATORY_INDEX: '抗炎指数',
  PRO_INFLAMMATORY: '促炎的',
  PRO_INFLAMMATORY_INDEX: '促炎指数',
  SUPPORTIVE_INDEX: '支持指数',
  GLYCAN_SHIELD: '少年糖链 (S)',
  GLYCAN_YOUTH: '青年糖链 (G2)',
  GLYCAN_MATURE: '老化糖链 (G0)',
  GLYCAN_MEDIAN: '中性糖链 (G1)',
  GLYCAN_LIFESTYLE: '受损糖链 (B)',
  GLYCAN_LIFESTYLE_B: '平分型糖链 (B)',
  WORSE: '更差',
  BETTER: '更好',
  OPTIMAL: '最佳',
  SUBOPTIMAL: '次优',
  AVERAGE: '平均',
  INDEX_SCORE: '指数分值',
  MEASURED_RESULT: '检查结果',
  POPULATION_AVERAGE: '人群平均',
  AGE: '年龄',
  SAME_AS: '同样',
  THAN: '更',
  YEAR_OLDER: '更老',
  YEARS_OLDER: '更老',
  YEAR_YOUNGER: '更年轻',
  YEARS_YOUNGER: '更年轻',
  AREA: '系统',
  CONDITION: '细分',
  OVERLAPS: '相关性',
  INDEX_OVERLAPS: '相关性',
  CARDIOVASCULAR: '心血管',
  CARDIOVASCULAR_HEALTH: '心血管',
  METABOLIC: '代谢',
  METABOLIC_HEALTH: '代谢',
  AUTOIMMUNE: '自身免疫',
  AUTOIMMUNE_HEALTH: '自身免疫',
  RESPIRATORY: '呼吸系统',
  RESPIRATORY_HEALTH: '呼吸系统',
  FEMALE: '仅女性',
  FEMALE_HEALTH: '仅女性',
  RISK_OF_HYPER: '高血压风险',
  PRE_HYPERTENSION: '高血压前期',
  HYPERTENSION: '高血压',
  MI_CVA: '心梗和卒中',
  ATHEROSCLEROSIS: '动脉粥样硬化',
  CORONARY: '冠心病',
  TYPE_2_DIABETES: 'II型糖尿病',
  DYSLIPIDEMIA: '高血脂',
  RHEUMATOID: '类风湿性关节炎',
  ULCERATIVE_COLITIS: '溃疡性结肠炎（UC)',
  CROHN: '克罗恩病',
  SLE: '系统性红斑狼疮（SLE)',
  COPD: '慢阻肺（慢性阻塞性肺病）COPD',
  PERIMENOPAUSE: '临绝经期/更年前期',
  NO_SIGNIFICANT_OVERLAP: '无相关性',
  RANKS_YOU_BEFORE: '您的结果优于',
  RANKS_YOU_AFTER: '的人',
  NO_SIGNIFICANT_AREAS: '没有需要注意的重要领域',
  SOME_AREAS: '一些需要注意的地方',
  SIGNIFICANT_AREAS: '值得关注的重要领域',
  SLIGHTLY_OUT_OF_RANGE: '稍微超出范围',
  SIGNIFICANTLY_OUT_OF_RANGE: '明显超出范围',
  AREAS_FOR_ATTENTION: '需要注意的地方',
  PLEASE_NOTE: '请注意',
  PLEASE_NOTE_SENTENCE: '虽然某些模式可能与在特定条件下观察到的模式相似，但这并不能证实疾病或任何亚临床形式的存在'
};

