export let english = {
  BIOLOGICAL_AGE: 'Biological age',
  CHRONOLOGICAL_AGE: 'Chronological age',
  CHRONOLOGICAL_AGE_TWO: 'chronological age',
  SI_SCORE: 'SI score',
  GLYCAN: 'Glycan',
  PEAK: 'Peak',
  LOWER_THAN_AVERAGE: 'Lower than average',
  BELOW_AVERAGE: 'Below average',
  AROUND_AVERAGE: 'Around average',
  HIGHER_THAN_AVERAGE: 'Higher than average',
  ABOVE_AVERAGE: 'Above average',
  SOME_OVERLAP_LONG: 'Some overlap',
  MINOR_OVERLAP_LONG: 'Minor overlap',
  NO_OVERLAP_LONG: 'No significant overlap',
  SOME_OVERLAP: 'Some overlap',
  MINOR_OVERLAP: 'Minor overlap',
  NO_OVERLAP: 'No significant overlap',
  OVERLAP_TEXT: 'of glycan indexes between your patient and this condition.',
  SYMPTOMS: 'Signs and symptoms',
  SYMPTOM_ONE: 'Usually asymptomatic',
  SYMPTOM_TWO: 'BP consistently >140/90 mmHg',
  SYMPTOM_THREE: 'Signs of malignant hypertension (headache, dizziness, breathlessness, etc.)',
  SYMPTOM_FOUR: 'Signs of coronary artery disease (e.g., self-resolving chest pain, breathlessness)',
  SYMPTOM_FIVE: 'Signs of peripheral artery disease (e.g., leg pain during activity)',
  SYMPTOM_SIX: 'Self-limiting chest pain ± radiation into jaw/left arm/back',
  SYMPTOM_SEVEN: 'Breathlessness',
  SYMPTOM_EIGHT: 'Other (syncope, palpitations, leg edema, orthopnea, etc.)',
  SYMPTOM_NINE: 'Abdominal pain and cramping/left arm/back',
  SYMPTOM_TEN: 'Recurring diarrhea (± blood)',
  SYMPTOM_TEN_B: 'Urgency to defecate',
  SYMPTOM_ELEVEN: 'Weight loss',
  SYMPTOM_TWELVE: 'Systemic (e.g., fatigue, weight loss, mouth ulcers, butterfly skin rash)',
  SYMPTOM_THIRTEEN: 'Organ-specific (chest pain, difficulty breathing, leg swelling, anaemia, etc.)',
  SYMPTOM_FOURTEEN: 'Joint pain and swelling',
  SYMPTOM_FIFTEEN: 'Fatigue',
  SYMPTOM_SIXTEEN: 'Increased thirst and frequent urination',
  SYMPTOM_SEVENTEEN: 'Slow wound healing, blurred vision, frequent thrush',
  SYMPTOM_EIGHTEEN: 'Difficulty breathing',
  SYMPTOM_NINETEEN: 'Chronic cough (± productive)',
  SYMPTOM_TWENTY: 'Irregular menstrual cycle',
  SYMPTOM_TWENTYONE: 'Vasomotor symptoms (e.g., hot flushes, night sweats)',
  SYMPTOM_TWENTYTWO: 'Other (e.g., mood swings, cognitive difficulties, sleep disturbance)',
  SYMPTOM_TWENTYTHREE: 'Joint pain, swelling, stiffness and erythema',
  SYMPTOM_TWENTYFOUR: 'Smaller and distant joint involvement (fingers, toes), usually symmetrical',
  SYMPTOM_TWENTYFIVE: 'Systemic (fatigue, weight loss, etc.)',
  POSSIBLE_FOLLOW_UP: 'Possible follow-up',
  POSSIBLE_FOLLOW_UP_ONE: 'Serial blood pressure (BP) measurements Â± 24-hour BP monitoring',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI and/or body composition check',
  POSSIBLE_FOLLOW_UP_THREE: 'Basic bloods (lipid profile, renal and liver function)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Blood tests: basic and extended lipid profile (e.g., Lp(a), ApoB), hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'BP check',
  POSSIBLE_FOLLOW_UP_SIX: 'ECG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Cardiology referral for other tests (e.g., cardiac echo, coronary CT)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Cardiology referral for other tests (e.g., coronary artery calcium score)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Cardiology referral for other tests (e.g., stress echocardiogram)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Blood tests: full blood count, renal and liver function, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Stool tests: faecal immunochemical test (FIT), faecal calprotectin',
  POSSIBLE_FOLLOW_UP_TEN: 'Referral for CT colonoscopy',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Blood tests: full blood count, renal and liver function, CRP, ESR, autoantibodies (e.g., ANA, anti-dsDNA)',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Urinalysis',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Organ-targeted imaging (e.g., CT thorax, CT abdomen)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Blood tests: full blood count, renal and liver function, fasting glucose and insulin, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Lipid profile blood tests: basic and extended (incl. oxLDL, VLDL, LDL-P, Lp-PLA2, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Other blood tests hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Blood tests: full blood count',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometry',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'ECG, chest X-ray',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Blood tests (incl. FSH, oestradiol, progesterone, testosterone, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Referral to (peri)menopause specialist/gynaecologist',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Blood tests: full blood count, rheumatoid factor, anti-CCP antibodies, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Joint imaging (X-rays, MRI)',
  PERCENTILE: 'percentile',
  SINGLE_PERCENTILE: 'percentile',
  RISK_FACTORS: 'Risk factors',
  RISK_FACTOR_ONE: 'Past medical history (cardiometabolic syndrome, autoimmune disease)',
  RISK_FACTOR_TWO: 'Medication history (e.g., statins, blood thinners)',
  RISK_FACTOR_THREE: 'Current/previous smoking history',
  RANKS_YOU: 'This result ranks you in the',
  THIS_RESULT_RANKS_IN_THE: 'This result ranks in the',
  RELATED_RESEARCH_PAPERS: 'Related research papers',
  YOUR_RESULT: 'Your result',
  CHRONIC_INFLAMMATION: 'Chronic inflammation',
  SYSTEMIC_INFLAMMATION: 'Systemic inflammation',
  ANTI_INFLAMMATORY: 'Anti-inflammatory',
  PRO_INFLAMMATORY: 'Pro-inflammatory',
  SUPPORTIVE_INDEX: 'Supportive index',
  GLYCAN_SHIELD: 'Glycan Shield (S)',
  GLYCAN_YOUTH: 'Glycan Youth (G2)',
  GLYCAN_MATURE: 'Glycan Mature (G0)',
  GLYCAN_MEDIAN: 'Glycan Median (G1)',
  GLYCAN_LIFESTYLE: 'Glycan Lifestyle (B)',
  WORSE: 'Worse',
  BETTER: 'Better',
  AVERAGE: 'Average',
  INDEX_SCORE: 'Index score',
  MEASURED_RESULT: 'Measured result',
  POPULATION_AVERAGE: 'Population average',
  AGE: 'Age',
  SAME_AS: 'Same as',
  THAN: 'than',
  YEAR_OLDER: 'year older',
  YEARS_OLDER: 'years older',
  YEAR_YOUNGER: 'year younger',
  YEARS_YOUNGER: 'years younger',
};

export let polish = {
  BIOLOGICAL_AGE: 'Wiek biologiczny',
  CHRONOLOGICAL_AGE: 'Wiek Kalendarzowy',
  GLYCAN: 'Glikan',
  PEAK: 'Pik',
  LOWER_THAN_AVERAGE: 'niższy od wartości średniej',
  AROUND_AVERAGE: 'W okolicach wartości średniej',
  HIGHER_THAN_AVERAGE: 'wyższy od wartości średniej',
  SOME_OVERLAP_LONG: 'Znaczny stopień pokrywania się',
  MINOR_OVERLAP_LONG: 'Nieznaczne stopień pokrywania się',
  NO_OVERLAP_LONG: 'Brak znaczącego pokrywania się',
  SOME_OVERLAP: 'Częściowy',
  MINOR_OVERLAP: 'Niewielki',
  NO_OVERLAP: 'Brak',
  OVERLAP_TEXT: 'indeksów glikanowych między pacjentem a badanymi z tym schorzeniem.',
  SYMPTOMS: 'Sygnały i objawy',
  SYMPTOM_ONE: 'Przeważnie przebiega w sposób bezobjawowy',
  SYMPTOM_TWO: 'Ciśnienie tętnicze stale >140/90 mmHg',
  SYMPTOM_THREE: 'Objawy nadciśnienia złośliwego (ból głowy, zawroty głowy, duszność itp.)',
  SYMPTOM_FOUR: 'Objawy choroby wieńcowej (np. samoistnie ustępujący ból w klatce piersiowej, bezdech)',
  SYMPTOM_FIVE: 'Objawy choroby tętnic obwodowych (np. ból nóg podczas aktywności)',
  SYMPTOM_SIX: 'Samoograniczający się ból w klatce piersiowej ± promieniujący do szczęki/lewego ramienia/pleców',
  SYMPTOM_SEVEN: 'Duszność',
  SYMPTOM_EIGHT: 'Inne (omdlenia, kołatanie serca, obrzęk nóg, orhhopnoe itp.)',
  SYMPTOM_NINE: 'Ból brzucha i skurcze',
  SYMPTOM_TEN: 'Nawracająca biegunka (± krew)',
  SYMPTOM_TEN_B: 'Nagła potrzeba wypróżnienia',
  SYMPTOM_ELEVEN: 'Utrata masy ciała',
  SYMPTOM_TWELVE: 'Ogólnoustrojowe (np. zmęczenie, utrata masy ciała, owrzodzenia jamy ustnej, wysypka w kształcie motyla w okolicy policzków i nosa)',
  SYMPTOM_THIRTEEN: 'Narządowe (ból w klatce piersiowej, trudności w oddychaniu, obrzęk nóg, niedokrwistość itp.)',
  SYMPTOM_FOURTEEN: 'Ból i obrzęk stawów',
  SYMPTOM_FIFTEEN: 'Zmęczenie',
  SYMPTOM_SIXTEEN: 'Zwiększone pragnienie i częste oddawanie moczu',
  SYMPTOM_SEVENTEEN: 'Powolne gojenie się ran, niewyraźne widzenie, częste pleśniawki',
  SYMPTOM_EIGHTEEN: 'Trudności w oddychaniu',
  SYMPTOM_NINETEEN: 'Przewlekły kaszel (± produktywny)',
  SYMPTOM_TWENTY: 'Nieregularny cykl menstruacyjny',
  SYMPTOM_TWENTYONE: 'Objawy naczynioruchowe (np. uderzenia gorąca)',
  SYMPTOM_TWENTYTWO: 'Inne (np. wahania nastroju, trudności poznawcze, zaburzenia snu)',
  SYMPTOM_TWENTYTHREE: 'Ból stawów, obrzęk, sztywność i rumień',
  SYMPTOM_TWENTYFOUR: 'Zajęcie mniejszych stawów dystalnych (palce rąk i nóg), zwykle symetryczne',
  SYMPTOM_TWENTYFIVE: 'Ogólnoustrojowe (zmęczenie, utrata masy ciała itp.)',
  POSSIBLE_FOLLOW_UP: 'Ewentualne dalsze działania',
  POSSIBLE_FOLLOW_UP_ONE: 'Seryjne pomiary ciśnienia tętniczego i/lub 24-godzinne monitorowanie ciśnienia tętniczego',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI i/lub kontrola składu ciała',
  POSSIBLE_FOLLOW_UP_THREE: 'Podstawowe badania krwi (profil lipidowy, czynność nerek i wątroby)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Badania krwi: podstawowy i rozszerzony profil lipidowy (np. Lp(a), ApoB), hsCRP, homocysteina, czynność nerek i wątroby, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'Kontrola ciśnienia tętniczego',
  POSSIBLE_FOLLOW_UP_SIX: 'EKG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Skierowanie do kardiologa na inne badania (np. echo serca, TK naczyń wieńcowych)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Skierowanie do kardiologa na inne badania (np. wskaźnik uwapnienia tętnic wieńcowych)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Skierowanie do kardiologa na inne badania (np. echokardiogram wysiłkowy)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Badania kału: test na obecność krwi utajonej (FIT), kalprotektyna w kale',
  POSSIBLE_FOLLOW_UP_TEN: 'Skierowanie na kolonoskopię, TK',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, CRP, OB, autoprzeciwciała (np. ANA, w tym anty-dsDNA).',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Badanie ogólne moczu',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Badania obrazowe ukierunkowane na narządy (np. TK klatki piersiowej, TK jamy brzusznej)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Badania krwi: pełna morfologia krwi, czynność nerek i wątroby, stężenie glukozy i insuliny na czczo, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Badania profilu lipidowego krwi: podstawowe i rozszerzone (np. oxLDL, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Inne badania krwi hsCRP, homocysteina, czynność nerek i wątroby, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Badania krwi: pełna morfologia krwi',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometria',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'EKG, RTG klatki piersiowej',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Badania krwi (w tym FSH, estradiol, progesteron, testosteron, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Skierowanie do specjalisty/ginekologa zajmującego się (peri)menopauzą',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Badania krwi: pełna morfologia krwi, czynnik reumatoidalny, przeciwciała anty-CCP, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Obrazowanie stawów (zdjęcia rentgenowskie, rezonans magnetyczny)',
  PERCENTILE: 'percentylu',
  SINGLE_PERCENTILE: 'percentyl',
  RISK_FACTORS: 'Czynniki ryzyka',
  RISK_FACTOR_ONE: 'Historia chorób (np. zespół kardiometaboliczny, choroby autoimmunologiczne)',
  RISK_FACTOR_TWO: 'Historia przyjmowania leków (np. statyn, leków przeciwzakrzepowych)',
  RISK_FACTOR_THREE: 'Palenie tytoniu',
  RANKS_YOU: 'Twoj wynik klasyfikuje Cię w',
  RELATED_RESEARCH_PAPERS: 'Publikacje naukowe',
  YOUR_RESULT: 'Twój wynik',
  CHRONIC_INFLAMMATION: 'TempText POLISH1',
  ANTI_INFLAMMATORY: 'TempText POLISH2',
  PRO_INFLAMMATORY: 'TempText POLISH3',
  SUPPORTIVE_INDEX: 'TempText POLISH4',
  GLYCAN_SHIELD: 'TempText Shield (S)',
  GLYCAN_YOUTH: 'TempText Youth (G2)',
  GLYCAN_MATURE: 'TempText Mature (G0)',
  GLYCAN_MEDIAN: 'TempText Median (G1)',
  GLYCAN_LIFESTYLE: 'TempText Lifestyle (B)',
  WORSE: 'TempText Worse',
  BETTER: 'TempText Better',
  AVERAGE: 'TempText Average',
};

export let slovenian = {
  BIOLOGICAL_AGE: 'Biološka starost',
  CHRONOLOGICAL_AGE: 'Kronološka starost',
  CHRONOLOGICAL_AGE_TWO: 'kronološke starosti',
  RANKS_YOU: 'Ta rezultat vas uvršča med',
  PERCENTILE: 'percentilov',
  SINGLE_PERCENTILE: 'percentil',
  YOUR_RESULT: 'Vaš rezultat',
  GLYCAN_SHIELD: 'Glikanski ščit (S)',
  GLYCAN_YOUTH: 'Mladost glikanov (G2)',
  GLYCAN_MATURE: 'Zrelost glikanov (G0)',
  GLYCAN_MEDIAN: 'Povprečje glikanov (G1)',
  GLYCAN_LIFESTYLE: 'Življenjski slog glikanov (B)',
  CHRONIC_INFLAMMATION: 'Kronično vnetje',
  ANTI_INFLAMMATORY: 'Protivnetni',
  PRO_INFLAMMATORY: 'Pro-vnetni',
  SUPPORTIVE_INDEX: 'Podporni kazalnik',
  WORSE: 'Slabše',
  BETTER: 'Boljše',
  AVERAGE: 'Povprečje',
  AROUND_AVERAGE: 'Približno povprečje',
  THIS_RESULT_RANKS_IN_THE: 'Ta rezultat se uvršča med',
  INDEX_SCORE: 'Rezultat kazalnika',
  MEASURED_RESULT: 'Vaš rezultat',
  POPULATION_AVERAGE: 'Povprečje prebivalstva',
  AGE: 'Dob',
  SAME_AS: 'Enako kot',
  THAN: 'od',
  YEAR_OLDER: 'starejši',
  YEARS_OLDER: 'starejši',
  YEAR_YOUNGER: 'let mlajši',
  YEARS_YOUNGER: 'let mlajši'
};

export let japanese = {
  BIOLOGICAL_AGE: '生物学的年齢',
  CHRONOLOGICAL_AGE: '暦年齢',
  CHRONOLOGICAL_AGE_TWO: '暦年齢',
  SI_SCORE: 'SI score',
  GLYCAN: 'Glycan',
  PEAK: 'Peak',
  LOWER_THAN_AVERAGE: 'Lower than average',
  BELOW_AVERAGE: 'Below average',
  AROUND_AVERAGE: '平均値くらい',
  HIGHER_THAN_AVERAGE: 'Higher than average',
  ABOVE_AVERAGE: 'Above average',
  SOME_OVERLAP_LONG: 'Some overlap',
  MINOR_OVERLAP_LONG: 'Minor overlap',
  NO_OVERLAP_LONG: 'No significant overlap',
  SOME_OVERLAP: 'Some overlap',
  MINOR_OVERLAP: 'Minor overlap',
  NO_OVERLAP: 'No significant overlap',
  OVERLAP_TEXT: 'of glycan indexes between your patient and this condition.',
  SYMPTOMS: 'Signs and symptoms',
  SYMPTOM_ONE: 'Usually asymptomatic',
  SYMPTOM_TWO: 'BP consistently >140/90 mmHg',
  SYMPTOM_THREE: 'Signs of malignant hypertension (headache, dizziness, breathlessness, etc.)',
  SYMPTOM_FOUR: 'Signs of coronary artery disease (e.g., self-resolving chest pain, breathlessness)',
  SYMPTOM_FIVE: 'Signs of peripheral artery disease (e.g., leg pain during activity)',
  SYMPTOM_SIX: 'Self-limiting chest pain ± radiation into jaw/left arm/back',
  SYMPTOM_SEVEN: 'Breathlessness',
  SYMPTOM_EIGHT: 'Other (syncope, palpitations, leg edema, orthopnea, etc.)',
  SYMPTOM_NINE: 'Abdominal pain and cramping/left arm/back',
  SYMPTOM_TEN: 'Recurring diarrhea (± blood)',
  SYMPTOM_TEN_B: 'Urgency to defecate',
  SYMPTOM_ELEVEN: 'Weight loss',
  SYMPTOM_TWELVE: 'Systemic (e.g., fatigue, weight loss, mouth ulcers, butterfly skin rash)',
  SYMPTOM_THIRTEEN: 'Organ-specific (chest pain, difficulty breathing, leg swelling, anaemia, etc.)',
  SYMPTOM_FOURTEEN: 'Joint pain and swelling',
  SYMPTOM_FIFTEEN: 'Fatigue',
  SYMPTOM_SIXTEEN: 'Increased thirst and frequent urination',
  SYMPTOM_SEVENTEEN: 'Slow wound healing, blurred vision, frequent thrush',
  SYMPTOM_EIGHTEEN: 'Difficulty breathing',
  SYMPTOM_NINETEEN: 'Chronic cough (± productive)',
  SYMPTOM_TWENTY: 'Irregular menstrual cycle',
  SYMPTOM_TWENTYONE: 'Vasomotor symptoms (e.g., hot flushes, night sweats)',
  SYMPTOM_TWENTYTWO: 'Other (e.g., mood swings, cognitive difficulties, sleep disturbance)',
  SYMPTOM_TWENTYTHREE: 'Joint pain, swelling, stiffness and erythema',
  SYMPTOM_TWENTYFOUR: 'Smaller and distant joint involvement (fingers, toes), usually symmetrical',
  SYMPTOM_TWENTYFIVE: 'Systemic (fatigue, weight loss, etc.)',
  POSSIBLE_FOLLOW_UP: 'Possible follow-up',
  POSSIBLE_FOLLOW_UP_ONE: 'Serial blood pressure (BP) measurements Â± 24-hour BP monitoring',
  POSSIBLE_FOLLOW_UP_TWO: 'BMI and/or body composition check',
  POSSIBLE_FOLLOW_UP_THREE: 'Basic bloods (lipid profile, renal and liver function)',
  POSSIBLE_FOLLOW_UP_FOUR: 'Blood tests: basic and extended lipid profile (e.g., Lp(a), ApoB), hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_FIVE: 'BP check',
  POSSIBLE_FOLLOW_UP_SIX: 'ECG',
  POSSIBLE_FOLLOW_UP_SEVEN: 'Cardiology referral for other tests (e.g., cardiac echo, coronary CT)',
  POSSIBLE_FOLLOW_UP_SEVEN_B: 'Cardiology referral for other tests (e.g., coronary artery calcium score)',
  POSSIBLE_FOLLOW_UP_SEVEN_C: 'Cardiology referral for other tests (e.g., stress echocardiogram)',
  POSSIBLE_FOLLOW_UP_EIGHT: 'Blood tests: full blood count, renal and liver function, CRP',
  POSSIBLE_FOLLOW_UP_NINE: 'Stool tests: faecal immunochemical test (FIT), faecal calprotectin',
  POSSIBLE_FOLLOW_UP_TEN: 'Referral for CT colonoscopy',
  POSSIBLE_FOLLOW_UP_ELEVEN: 'Blood tests: full blood count, renal and liver function, CRP, ESR, autoantibodies (e.g., ANA, anti-dsDNA)',
  POSSIBLE_FOLLOW_UP_TWELVE: 'Urinalysis',
  POSSIBLE_FOLLOW_UP_THIRTEEN: 'Organ-targeted imaging (e.g., CT thorax, CT abdomen)',
  POSSIBLE_FOLLOW_UP_FOURTEEN: 'Blood tests: full blood count, renal and liver function, fasting glucose and insulin, HbA1c, HOMA-IR',
  POSSIBLE_FOLLOW_UP_FIFTEEN: 'Lipid profile blood tests: basic and extended (incl. oxLDL, VLDL, LDL-P, Lp-PLA2, Lp(a), ApoB))',
  POSSIBLE_FOLLOW_UP_SIXTEEN: 'Other blood tests hsCRP, homocysteine, renal and liver function, HbA1c',
  POSSIBLE_FOLLOW_UP_SEVENTEEN: 'Blood tests: full blood count',
  POSSIBLE_FOLLOW_UP_EIGHTEEN: 'Spirometry',
  POSSIBLE_FOLLOW_UP_NINETEEN: 'ECG, chest X-ray',
  POSSIBLE_FOLLOW_UP_TWENTY: 'Blood tests (incl. FSH, oestradiol, progesterone, testosterone, AMH)',
  POSSIBLE_FOLLOW_UP_TWENTYONE: 'Referral to (peri)menopause specialist/gynaecologist',
  POSSIBLE_FOLLOW_UP_TWENTYTWO: 'Blood tests: full blood count, rheumatoid factor, anti-CCP antibodies, CRP',
  POSSIBLE_FOLLOW_UP_TWENTYTHREE: 'Joint imaging (X-rays, MRI)',
  PERCENTILE: 'パーセンタイル',
  SINGLE_PERCENTILE: 'パーセンタイル',
  RISK_FACTORS: 'Risk factors',
  RISK_FACTOR_ONE: 'Past medical history (cardiometabolic syndrome, autoimmune disease)',
  RISK_FACTOR_TWO: 'Medication history (e.g., statins, blood thinners)',
  RISK_FACTOR_THREE: 'Current/previous smoking history',
  RANKS_YOU: 'この結果により、あなたは',
  THIS_RESULT_RANKS_IN_THE: 'この結果は、',
  RELATED_RESEARCH_PAPERS: 'Related research papers',
  YOUR_RESULT: 'Your result',
  CHRONIC_INFLAMMATION: '慢性炎症',
  SYSTEMIC_INFLAMMATION: '全身性炎症',
  ANTI_INFLAMMATORY: '抗炎症性',
  PRO_INFLAMMATORY: '炎症誘発性',
  SUPPORTIVE_INDEX: 'サポート指標',
  GLYCAN_SHIELD: 'Glycan Shield (S)',
  GLYCAN_YOUTH: 'Glycan Youth (G2)',
  GLYCAN_MATURE: 'Glycan Mature (G0)',
  GLYCAN_MEDIAN: 'Glycan Median (G1)',
  GLYCAN_LIFESTYLE: 'Glycan Lifestyle (B)',
  WORSE: 'より年上',
  BETTER: 'より若い',
  AVERAGE: '平均値',
  INDEX_SCORE: '指標スコア',
  MEASURED_RESULT: 'あなたの結果',
  POPULATION_AVERAGE: '母集団平均',
  AGE: '年齢',
  SAME_AS: '〜と同じ',
  THAN: 'より',
  YEAR_OLDER: '年上',
  YEARS_OLDER: '年上',
  YEAR_YOUNGER: '年下',
  YEARS_YOUNGER: '年下',
};
